### ISSUE TITLE
OVF Tool error: Invalid target datastore specified (ESXi)

### ISSUE THREAD

**Issue by boroborob** [josenk/vagrant-vmware-esxi#1]
Hi!

I am trying to bring up the default vm with vagrant on my ESXi 6.5 (update 1) server, but it always fails with the error above:

[test@test ~]$ vagrant up
Bringing machine 'default' up with 'vmware_esxi' provider...
==> default: Virtual Machine will be built.
==> default: --- WARNING       : unraid_ssd not found, using ESXi.
==> default: --- ESXi host       : *****
==> default: --- VM Name         : V-test-test-test
==> default: --- CPUS            : 1
==> default: --- Memsize (MB)    : 512
==> default: --- Guest OS type   : ubuntu-64
==> default: --- Disk Store      : ESXi
==> default: --- NetworkName     : "VM Network"
==> default: --- Resource Pool   : 
VMware ovftool 4.2.0 (build-5965791)
Opening VMX source: /home/test/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-precise64/1.1.0/vmware_fusion/ZZZZ_V-test-test-test.vmx
Opening VI target: vi://root@10.10.10.3:443/
Error: Invalid target datastore specified (ESXi): Possible completions: 
  ESXi USB 
  unraid_ssd 
Completed with errors
There was an OVF Tool error.
  
[test@test ~]$

The available datastores are listed correctly after the error.
It doesn't matter which if I select one of the two available datastores or just leave it at default in the Vagrantfile.

Found this forum topic about a similar problem: https://communities.vmware.com/thread/428328

Thanks

**Comment by josenk** [comment]
Can you send me the output of df -h from your ESXi box.

  Also, the site mentioned that you get the error if you have any ds in a directory...  Is that your case?
or do you have spaces in the DS names?

**Comment by boroborob** [comment]
Here is my df -h output:

Filesystem   Size   Used Available Use% Mounted on
NFS        232.9G  54.7G    178.2G  23% /vmfs/volumes/unraid_ssd
VMFS-6      19.8G  14.9G      4.9G  75% /vmfs/volumes/ESXi USB
vfat       249.7M 148.4M    101.3M  59% /vmfs/volumes/f9ff18e4-a1d686b1-f690-3b1c2e4df9ae
vfat       249.7M 148.5M    101.2M  59% /vmfs/volumes/79ec33e8-67c51262-5041-8b0215ff5849
vfat       285.8M 207.0M     78.8M  72% /vmfs/volumes/59a47f6e-d200c45a-ba8b-001e67393c74

I saw that in lib/vagrant-vmware-esxi/action/createvm.rb you grep to VMFS, tried to modify/remove it, but that only resulted in errors. Would it be possible to include NFS datastores as well?

`            #  Figure out DataStore
            r = ssh config.esxi_hostname,
                    'esxcli storage filesystem list | '\
                    'grep "/vmfs/volumes/.*true  VMFS" | sort -nk7'`

Initially I had space in both ds names, like: ESXi USB and Unraid SSD.
Then I renamed them with underscore instead of a space, but that didn't help either.

**Comment by josenk** [comment]
﻿Hello,



   I changed the way I check for Disk Storage...   It should now allow DS with spaces and it also works with NFS.   Please try attached and let me know how it works out.



Thanks for the feedback!



 Jonathan







-----Original message-----

**Comment by boroborob** [comment]
Hi Jonathan,

I can't seem to find any attachments.
Could you please send it again? 

Thanks!
Rob

**Comment by josenk** [comment]
Ahhh, no attachments here...   I just published V1.14.  Please update your vagrant plugins and retry.
Thanks,  Jonathan

**Comment by boroborob** [comment]
Thanks, now it's working perfectly. :)
Tested with and without spaces.

Will play around with it during the weekend.

Thanks again for your work!
