### ISSUE TITLE
centos/7 image, in vmx file the guestOS is "linux" not "centos7-64"

### ISSUE THREAD

**Issue by rodrigc** [josenk/vagrant-vmware-esxi#100]
I have a Vagrantfile with something like:

```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
```

When I use this Vagrantfile and install with vagrant-vmware-esxi on ESXi,
in the .vmx file of the vm, I get:

`guestOS = "linux"`

I would prefer:

`guestOS = "centos7-64"`

Is there a way that I can get that when I create the VM's?

Right now I have been logging into the ESXi server and manually editing the .vmx file.

**Comment by josenk** [comment]
It's in the readme...   You should be able to do the change using guest_guestos variable in your Vagrantfile.

**Comment by Makr91** [comment]
Did want to have to do a merge process but centos8-64 works for me on CentOS 8 boxes. Might want to add that to the wiki

**Comment by josenk** [comment]
It's in the README and the example Vagrantfile...
