### ISSUE TITLE
i18n version conflict

### ISSUE THREAD

**Issue by ankycooper** [josenk/vagrant-vmware-esxi#102]
When I install esxi plugin it complains of version conflict on ubuntu 18.04

`Installing the 'vagrant-vmware-esxi' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies i18n (~> 1.0) and i18n (= 0.7.0)
  Activated i18n-0.7.0
  which does not match conflicting dependency (~> 1.0)

  Conflicting dependency chains:
    i18n (= 0.7.0), 0.7.0 activated

  versus:
    vagrant-vmware-esxi (> 0), 2.4.2 activated, depends on
    i18n (~> 1.0)

`

**Comment by josenk** [comment]
You have something on your system that depends on i18n (0.7.0) from 2014!   I'm already pretty generous to set a dependency of 1.x.x.
>https://rubygems.org/gems/i18n/versions

**Comment by zensonic** [comment]
Debian has issue when trying to use vagrant from debian (instead of upstream) and non-debian vagrant plugins. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896904 

Solution: remove debian vagrant. Install upstream. Happy life.
