### ISSUE TITLE
Make it easier to troubleshoot authentication errors

### ISSUE THREAD

**Issue by rgl** [josenk/vagrant-vmware-esxi#103]
Instead of an opaque message alike:

```
==> default: --- ESXi host access : Verify password in Vagrantfile is correct.
There was an error talking to ESXi.
  Unable to connect to ESXi host!
```

It would helped if this returned:

```
==> default: --- ESXi host access : Verify password in Vagrantfile is correct.
There was an error talking to ESXi.
  Unable to connect to ESXi host due to fingerprint SHA256:74N24U4n0HykvIbokUIoPZr306T+0sV3Yq6VgUexac8 does not match for "esxi.test,192.168.121.52"!
```

This more helpful error message can be done by changing https://github.com/josenk/vagrant-vmware-esxi/blob/bac5b6db49afee2068e4f58c41a80d11d7518a77/lib/vagrant-vmware-esxi/action/esxi_password.rb#L204-L205 to be:

```ruby
              raise Errors::ESXiError,
                    message: "Unable to connect to ESXi host due to #{$!}!"
```

Let me known if I can submit a PR with this change.

**Comment by josenk** [comment]
Sure, submit a PR.... Yes, it's certainly more informative to display the actual error.
