### ISSUE TITLE
config.esxi_hostport is not used

### ISSUE THREAD

**Issue by radimch** [josenk/vagrant-vmware-esxi#105]
The config.esxi_hostport should be used when generating **clone_from_vm_path**
I defaults to 22 IMHO now.
https://github.com/josenk/vagrant-vmware-esxi/blob/333a7c1641daf92e27927dd3e3a2d4e822d0f5a6/lib/vagrant-vmware-esxi/action/createvm.rb#L94

**Comment by radimch** [comment]
moreover it then wants to reach 
https://#{config.esxi_hostname}/sdk/vimServiceVersions.xml
that may also be on a different port (not 443)
leading to ERROR **404**

**Comment by josenk** [comment]
esxi_hostport is used to specify the ssh port...

**Comment by radimch** [comment]
yes, OK got it. Maybe my description was unclear.

Simply said:
my esxi host's ssh used to run on port _different than 22_
In such a case _vagrant up_ didn't work - it failed with

> Error: cURL error: Couldn't connect to server
> Completed with errors
> There was an OVF Tool error.

When I changed esxi host's ssh port to 22, this part passed without error,
but it failed a little bit after _(and that in was my second misleading comment)_ with:
> Error: Could not open URL https://${my_ESXI_HOST}/sdk/vimServiceVersions.xml (response code: 404)
> Completed with errors
> There was an OVF Tool error.

because even my esxi machine https didn't run on the default https 443 port.

BUT when I changed
both ESXi host's ssh port to 22 and https port to 443 the build
_vagrant up_ passed completely OK.

**Comment by radimch** [comment]
ad 1. No. It works if-and-ONLY-if the esxi_hostport equals to 22 

ad 2. Yes, you are right. This should be a separate feature request. Sorry for messing the issue with this.

**Comment by josenk** [comment]
A quick review of all my ssh connections in code does use esxi_hostport.

In your example, you say you changed port 22, but got a cURL error (from ovftool)  ovftool uses port 443.  I don't see how changing the ssh port can affect ovftool...    Can you repeat you tests, but only change the ssh port (22).
