### ISSUE TITLE
Not updating number of virtual CPUs during VM deployment

### ISSUE THREAD

**Issue by erorpetar** [josenk/vagrant-vmware-esxi#106]
Hi,

I'm using this awesome plugin with vagrant 2.2.9 and ovftool  4.4.0 on ESXi 6.7U2.

I found out that during commissioning number of vCPU were not updated to values I provided using:

esxi.guest_numvcpus

After debug I found out that ovftool is not creating numvcpus="x" in generated vmx file so VM gets the same number of vCPUs as "template".

At the moment I resolved it by adding:

--numberOfCpus

to ovftool command in createvm.rb.

I guess this requires some reparations in plugin.

**Comment by josenk** [comment]
I'm not sure I fully understand...
> I found out that ovftool is not creating numvcpus="x" in generated vmx file so VM gets the same number of vCPUs as "template".

How can the new VM be configured with the same number of cpus as the source, if you said it doesn't add the numvcpus="x" variable???

BTW:  If ovftool is not doing it's job correctly, it's a bug with ovftool...

**Comment by erorpetar** [comment]
I'll try to explain...

esxi.guest_numvcpus in my Vagrantfile was not updating number of CPUs on the VM I deployed. Deployed VM still has same number of CPUs as source VM I used not the number of CPUs I tried to set using previous parameter. 

It's related to ovftool but it is just a matter of parameters in ovftool command not bug in it.

BR, 

Petar

**Comment by josenk** [comment]
I will need a way to recreate the problem...  I have not experienced this issue.  Something similar has been reported with the terraform plugin (that also uses ovftool), but the end-user was not able to provide me with enough details to recreate the issue.

How was that original source VM created?  What is your pc/laptop OS you are using?  What version of Vagrant & Plugin are you using?

Please upload your Vagrantfile, the source and destination vmx file(located on the esxi host).  

Please update your Vagrantfile with esxi.debug = 'true vmx' and send the output of your `vagrant up` command.
>https://github.com/josenk/vagrant-vmware-esxi/wiki/Debugging-the-plugin
