### ISSUE TITLE
custom_vmx_settings are not being transferred by ovftool to ESXI server

### ISSUE THREAD

**Issue by skorada-rvbd** [josenk/vagrant-vmware-esxi#11]
Hi,

I am trying to bring up VMs on my ESXI server (6.5) using the plugin. In the Vagrantfile I have defined some custom_vmx_settings to enable hardware virtualization.

Vagrantfile:

_VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.forward_agent = true
  config.vm.define CFG_MASTER_NODE_NAME do |x|
    x.vm.box = "bento/ubuntu-16.04"
    x.vm.provider :vmware_esxi do |v|
      v.esxi_hostname = '10.73.40.19'
      v.esxi_username = 'root'
      v.esxi_password = 'mypassword'
      v.custom_vmx_settings = [['vhv.enable', 'TRUE']]   **===> CUSTOM SETTING**
      v.vmname = 'test_vm'
      v.memsize = "6144"
      v.numvcpus = "4"
    end
    x.vm.provision :shell do |s|
       s.path = CFG_MASTER_NODE_PROVISION_SCRIPT
       s.args = ["-m", CFG_SDP_USER_PASSWD, CFG_SDP_SRC_FROM_BRANCH, CFG_SDP_SRC_FROM_TAG, CFG_SDP_LAN_INTERFACE, CFG_SDP_WAN_INTERFACE, CFG_SDP_OPTIONAL_INSTALL_PARAMS ]
    end
  end
end_

The vmx file that is created on the machine where ovftool is running is as such and includes the custom settings , vhv.enable="TRUE"

The vmx file passed on to ovftool:

_.encoding = "UTF-8"
bios.bootorder = "hdd,CDROM"
checkpoint.vmstate = ""
cleanshutdown = "TRUE"
config.version = "8"
cpuid.corespersocket = "1"
displayname = "test_vm"
ehci.pcislotnumber = "-1"
ehci.present = "FALSE"
extendedconfigfile = "ubuntu-16.04-amd64.vmxf"
floppy0.present = "FALSE"
guestos = "ubuntu-64"
gui.fullscreenatpoweron = "FALSE"
gui.viewmodeatpoweron = "windowed"
hgfs.linkrootshare = "TRUE"
hgfs.maprootshare = "TRUE"
ide1:0.clientdevice = "TRUE"
ide1:0.devicetype = "cdrom-raw"
ide1:0.filename = "auto detect"
ide1:0.present = "TRUE"
isolation.tools.hgfs.disable = "FALSE"
memsize = "6000"
migrate.hostlog = "./ubuntu-16.04-amd64-9eff85f8.hlog"
monitor.phys_bits_used = "40"
msg.autoanswer = "true"
numa.autosize.cookie = "10001"
numa.autosize.vcpu.maxpervirtualnode = "1"
numvcpus = "2"
nvram = "ubuntu-16.04-amd64.nvram"
pcibridge0.pcislotnumber = "17"
pcibridge0.present = "TRUE"
pcibridge4.functions = "8"
pcibridge4.pcislotnumber = "21"
pcibridge4.present = "TRUE"
pcibridge4.virtualdev = "pcieRootPort"
pcibridge5.functions = "8"
pcibridge5.pcislotnumber = "22"
pcibridge5.present = "TRUE"
pcibridge5.virtualdev = "pcieRootPort"
pcibridge6.functions = "8"
pcibridge6.pcislotnumber = "23"
pcibridge6.present = "TRUE"
pcibridge6.virtualdev = "pcieRootPort"
pcibridge7.functions = "8"
pcibridge7.pcislotnumber = "24"
pcibridge7.present = "TRUE"
pcibridge7.virtualdev = "pcieRootPort"
powertype.poweroff = "soft"
powertype.poweron = "soft"
powertype.reset = "soft"
powertype.suspend = "soft"
proxyapps.publishtohost = "FALSE"
remotedisplay.vnc.enabled = "FALSE"
remotedisplay.vnc.ip = "127.0.0.1"
remotedisplay.vnc.key = "KyokGBcvGh0mOgsxOzIoJSwpDSYfNxQtDx0tAzYxCwUnNQUILxgtNzsRNyIdKwEUFx4uFD07ORY2ChYlKz0BGz8PJCYqJw4iJS84CjMNOQI5MTAxMj4sEz0/OzAYGhAqGS44Fx4dIg8aFxU4Jh8KKzMvGRotBgcMMhwZLzU3MBE="
remotedisplay.vnc.password = "wajQzFV1"
remotedisplay.vnc.port = "5903"
replay.filename = ""
replay.supported = "FALSE"
scsi0.pcislotnumber = "16"
scsi0.present = "TRUE"
scsi0.virtualdev = "lsilogic"
scsi0:0.filename = "disk.vmdk"
scsi0:0.present = "TRUE"
scsi0:0.redo = ""
softpoweroff = "TRUE"
sound.startconnected = "FALSE"
tools.synctime = "TRUE"
tools.upgrade.policy = "upgradeAtPowerCycle"
usb.pcislotnumber = "-1"
usb.present = "FALSE"
uuid.action = "create"
uuid.bios = "56 4d 41 16 a3 f7 91 52-6b 79 18 92 29 63 11 af"
uuid.location = "56 4d 41 16 a3 f7 91 52-6b 79 18 92 29 63 11 af"
virtualhw.productcompatibility = "hosted"
virtualhw.version = "9"
vmci0.id = "1861462627"
vmci0.pcislotnumber = "35"
vmci0.present = "TRUE"
vmotion.checkpointfbsize = "67108864"
ethernet0.networkName = "net0"
ethernet0.present = "TRUE"
ethernet0.addressType = "generated"
vhv.enable = "TRUE"_ . **==> This has the custom settings.**

Now when the ovf deploys on the ESXI server and the VM comes up , the vmx file on the server doesnt have this setting.

From the server:

_.encoding = "UTF-8"
config.version = "8"
virtualHW.version = "9"
pciBridge0.present = "TRUE"
svga.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
vmci0.present = "TRUE"
hpet0.present = "TRUE"
floppy0.present = "FALSE"
numvcpus = "2"
memSize = "6000"
powerType.suspend = "soft"
tools.upgrade.policy = "upgradeAtPowerCycle"
scsi0.virtualDev = "lsilogic"
scsi0.present = "TRUE"
ide1:0.startConnected = "FALSE"
ide1:0.deviceType = "atapi-cdrom"
ide1:0.fileName = "CD/DVD drive 0"
ide1:0.present = "TRUE"
scsi0:0.deviceType = "scsi-hardDisk"
scsi0:0.fileName = "test_vm.vmdk"
scsi0:0.present = "TRUE"
ethernet0.networkName = "VM Network"
ethernet0.addressType = "generated"
ethernet0.present = "TRUE"
displayName = "test_vm"
guestOS = "ubuntu-64"
toolScripts.afterPowerOn = "TRUE"
toolScripts.afterResume = "TRUE"
toolScripts.beforeSuspend = "TRUE"
toolScripts.beforePowerOff = "TRUE"
tools.syncTime = "TRUE"
uuid.bios = "56 4d ab 85 aa 1f 1f 71-f1 50 ae 56 25 12 a6 2b"
uuid.location = "56 4d ab 85 aa 1f 1f 71-f1 50 ae 56 25 12 a6 2b"
vc.uuid = "52 cd c0 d1 46 5e ab 73-87 ff ae 1b f2 e5 aa ad"
nvram = "test_vm.nvram"
virtualhw.productcompatibility = "hosted"
numa.autosize.vcpu.maxPerVirtualNode = "2"
numa.autosize.cookie = "20001"
sched.swap.derivedName = "/vmfs/volumes/59f6e862-9a92cb8a-bc8a-246e96135a98/test_vm/test_vm-8b4a323e.vswp"
migrate.hostlog = "./test_vm-1-8b4a323e.hlog"
scsi0:0.redo = ""
pciBridge0.pciSlotNumber = "17"
pciBridge4.pciSlotNumber = "21"
pciBridge5.pciSlotNumber = "22"
pciBridge6.pciSlotNumber = "23"
pciBridge7.pciSlotNumber = "24"
scsi0.pciSlotNumber = "16"
ethernet0.pciSlotNumber = "32"
vmci0.pciSlotNumber = "33"
ethernet0.generatedAddress = "00:0c:29:12:a6:2b"
ethernet0.generatedAddressOffset = "0"
vmci0.id = "621979179"
monitor.phys_bits_used = "40"
vmotion.checkpointFBSize = "4194304"
cleanShutdown = "FALSE"
softPowerOff = "FALSE"_

I am not sure what I could be missing here.All the other configs I have set in the Vagrantfile are visible on the vmx file on the server.
Is this an issue with the config_version hardcoded to 8 , which translates to ESXI 5.1? Could you please help?

Thanks

**Comment by josenk** [comment]
Good catch!   Using an undocumented feature...   ;-)

It was undocumented because it hasn't really been tested much.  There are many types of sources and destinations that ovftool supports...   I'm not 100% sure how ovftool does it, but I believe ovftool will use some type of whitelist/blacklist to create the destination guest.   For example, some guests will only work with certain network drivers, so ovftool will need to adjust for that if the source is saying to use an invalid driver.

My latest plugin puts the custom_vmx_setting on the ESXi host (append to the destination vmx file) after it's been transferred, so now it should work...   However!!!   The downside.   If you put something invalid or unsupported, your guest will NOT power up.   Use vSphere  to debug.

Please try updating to V1.4.0 and let me know if it fixes your problem.

**Comment by skorada-rvbd** [comment]
With the latest fixes/plugin this is now working.
Thanks a lot!

**Comment by josenk** [comment]
Great!  Thanks for the feedback...   I'll do more testing and update documentation to explain custom_vmx_settings.
