### ISSUE TITLE
Vagrant snapshot restore fails when the VM is already down

### ISSUE THREAD

**Issue by arunbadri** [josenk/vagrant-vmware-esxi#110]
Hi 

Not sure sure if this is expected usecase where if I bring down VM's by 
**vagrant halt** 
and then do 
**vagrant snapshot restore <snapshot_name>**

the plugin attempts to stop again the VM's which is already down and fails saying it cannot stop the VM and hence can't restore it.

**Comment by josenk** [comment]
That wouldn't be the expected behaviour...  The snapshot restore should work regardless of the current state.  I'll be able to do a fix pretty easily and quickly.

**Comment by josenk** [comment]
Should be fixed now in v2.5.2
> https://github.com/josenk/vagrant-vmware-esxi/releases/tag/v2.5.2

Update the plugin and it should now work as expected.

**Comment by arunbadri** [comment]
> the plugin and it should now work as expected.

Works great now after updating the plugin. Thank you. Appreciate it
