### ISSUE TITLE
Could there be functionality to use vm.box_url for getting the store template and build on it.

### ISSUE THREAD

**Issue by arunbadri** [josenk/vagrant-vmware-esxi#111]
Hi,

Could there be functionality to use vm.box_url for getting the stored template and build VM by referencing the respective template. I know only VCenter supports it. Does that give any api to use inside the plugin so that it avoids copying vagrant flavour of OS and instead use custom template which is specific to the requirement can be used.

Thanks,

**Comment by josenk** [comment]
As far as I know, standalone esxi doesn't support templates.  This plugin is for standalone esxi..
