### ISSUE TITLE
Deploy of vmx file fails @75%, some works and most fails 

### ISSUE THREAD

**Issue by arunbadri** [josenk/vagrant-vmware-esxi#113]
Opening VMX source: /home/xxxx/.vagrant.d/boxes/centos-VAGRANTSLASH-7/2004.01/vmware_desktop/ZZZZ_kworker1.vmx
Opening VI target: vi://root@xxxxxx:443/
Deploying to VI: vi://root@1xxxxxx0:443/
**Transfer Failed                       
Error: Failed to transfer file [kworker1-0.vmdk] to host [xxxxxx] (response code:500)
Completed with errors
There was an OVF Tool error.**

Is there a socket timeout or anything issue with the ovf tool ?

**Version:**

 ```
% vagrant version; vagrant plugin list 

Installed Version: 2.2.10
Latest Version: 2.2.13
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/hashicorp/vagrant/blob/v2.2.13/CHANGELOG.md
vagrant-vmware-esxi (2.5.2, global)

```

**Comment by josenk** [comment]
Not sure how much I can help you here...  You didn't provide any details other than it falls 75% of the time???   What is "it"?  I'm not even sure if the same vmx works 25%, or 25% of your vmx vms always works...

Enable debugging to get the ovftool command used.  Then run it manually, if you cannot make it work manually, it will not work inside the plugin.

There seems to be many google hits when you search for "ovftool bad response 500".

If you feel there's an issue with the plugin, please post more details about the issue including the debug output and your Vagrantfile.

**Comment by arunbadri** [comment]
Hi @josenk 

Thanks for the response. I guess found the cause this time. 
It is my own environment having multiple vm(2 ubuntu desktop) running locally on my VMWare workstation.

May be the host network is overwhelmed for some reason and chopping the connections. When I stopped other VM and kept the current ubuntu VM having this plugin running, it worked fine .

So I guess it is mostly the desktop issue.. and we can close this. 

Thank you,

**Comment by arunbadri** [comment]
This is more of environment issue with both client and as well as the datastore (least used datastore) writing disc when that disk is very slow.
