### ISSUE TITLE
Guest VM defaults to 40G, even after setting guest_boot_disk_size value 

### ISSUE THREAD

**Issue by arunbadri** [josenk/vagrant-vmware-esxi#114]
I set to boot disk to 15GB , but the VM guest always starts with 40G and below warning is seen - 
** WARNING         : Unable to extend Boot Disk to 15GB**

Anything I'm missing ?

```

==> kmaster1: ---  --- Guest Summary ---
==> kmaster1: --- VM Name         : kmaster1
==> kmaster1: --- Box             : centos/7
==> kmaster1: --- Box Ver         : 2004.01
==> kmaster1: --- Memsize (MB)    : 4096
==> kmaster1: --- CPUS            : 4
**==> kmaster1: --- Boot Disk Size  : 15GB**
==> kmaster1: --- Guest OS type   : linux
==> kmaster1: ---   --- Guest Build ---
Opening VMX source: /home/xxxxx/.vagrant.d/boxes/centos-VAGRANTSLASH-7/2004.01/vmware_desktop/ZZZZ_kmaster1.vmx
Opening VI target: vi://root@xxxxxxx:443/
Deploying to VI: vi://root@xxxxxx:443/
Transfer Completed                    
Completed successfully
==> kmaster1: --- VMID            : 49
**==> kmaster1: --- WARNING         : Unable to extend Boot Disk to 15GB**
==> kmaster1: --- VM has been Powered On...
==> kmaster1: --- Waiting for state "running"
==> kmaster1: --- Success, state is now "running"
==> kmaster1: --- Configuring     : 172.16.16.201/255.255.0.0 on VM Network
    kmaster1: 
```

vagrant file entries

```
kmaster.vm.provider "vmware_esxi" do |v|
        v.esxi_disk_store =  'datastore1'
        v.guest_boot_disk_size = '15'
        # v.guest_storage = '20'
        v.esxi_virtual_network = ['VM Network','VM Network']
        v.esxi_hostname = 'xxxxxxxx'
        v.esxi_username = 'root'
        v.esxi_password = 'file:my_sec_file'
        v.guest_name = "kmaster#{i}"
        v.guest_memsize = '4096'
        v.guest_numvcpus = '4'

```

**Comment by josenk** [comment]
How big is the original disk?  You can only extend disks, not reduce them.

**Comment by arunbadri** [comment]
The datastore is 924GB. 672GB has been used and remaining is left for new VM creation.
![image](https://user-images.githubusercontent.com/40041595/99194452-642a0900-2777-11eb-8ca5-e587eaccd093.png)

**Comment by josenk** [comment]
How big is the original disk? You can only extend disks, not reduce them

**Comment by arunbadri** [comment]
It is 1.1 G the vmdk file
![image](https://user-images.githubusercontent.com/40041595/99197764-69458300-278c-11eb-8fc9-d65bc720a44a.png)

**Comment by josenk** [comment]
The size on disk doesn't represent it's provisioned size.  It's sparse (thin provioned).  Don't specify a new root didk size.   The plugin will transfer it as-is and you'll see it's provisioned size. My guess is its 40gb.

**Comment by arunbadri** [comment]
Hi @josenk,

Yes, I see that without mentioning it is 40GB thin sizing.. but wanted to have it reduced to 20 or 15G instead of 40G by default. So just to clarify when you say plugin will transfer it as-is and sets to 40G, can't that be changed to user value. Is the default set it in ovftool?

Thanks,

**Comment by josenk** [comment]
`So just to clarify when you say plugin will transfer it as-is and sets to 40G,`  I didn't actually say that...   I said "The plugin will transfer it as-is and you'll see it's provisioned size."  So what that means is whoever created that Vagrant Box,   --->> THEY created the boot disk with a 40G root disk.<<--- 

   If you really want a 15GB boot disk, then you'll need to create a new Box (yourself).   However, since it's thin provisioned, it shouldn't really matter...

**Comment by arunbadri** [comment]
Got it . Thanks for the information. That helps. I just wondering where it came from in the beginning.. Now I got it. I'll close this.
