### ISSUE TITLE
Request for new password option - pipe from command

### ISSUE THREAD

**Issue by Curtis-rmc-06** [josenk/vagrant-vmware-esxi#115]
First, thanks for this great plugin!  It's greatly streamlined my process this far.

I'm weary about having my esxi password left as plaintext in a file or environment variable.

I have no experience with Ruby, but hoping it's not too much to ask for a feature request to have a pipe option for "esxi.esxi_password"

I use a yubikey and pass to keep my passwords safe, and this option would further streamline my process for vm deployment, and assume this feature would help anyone using a password manager.

Thanks!

**Comment by josenk** [comment]
To do that, you are actually piping the password to vagrant, not the plugin.  It doesn't look like vagrant is able to accept any stdin...  BTW:   Piping the password to stdin of vagrant doesn't make anything more secure...

You can do something like this.

In your Vagrantfile.
```
    e.esxi_password = 'env:ESXIPASSSORD'
```

In your bash shell script.

```
!#/bin/bash


#  or use whatever method you are using to get the PW...
echo "enter your password:"  
read key

export ESXIPASSSORD=${key}

vagrant up
```

When your shell script closes, the environment variable is destroyed.
