### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication

### ISSUE THREAD

**Issue by SLongofono** [josenk/vagrant-vmware-esxi#120]
This is run from a fresh install of CentOS 8, working to clone an existing CentOS 8 vm called vm-template.

Vagrant hung on "waiting for state running."  When I opened the vm and logged in via the ESXI management interface, this resolved, and I saw the error below:

```
Bringing machine 'default' up with 'vmware_esxi' provider...
==> default: Virtual Machine will be built.
VMware ovftool 4.4.0 (build-16360108)
Opening VI source: vi://root@esxi:443/vm-template
Opening VMX target: /tmp/d20210922-4860-b5t20z
Writing VMX file: /tmp/d20210922-4860-b5t20z/vm-template/vm-template.vmx
Transfer Completed
Completed successfully
==> default: ---   --- ESXi Summary ---
==> default: --- ESXi host       : esxi
==> default: --- Virtual Network : ["Network0", "Network1"]
==> default: --- Disk Store      : RAID_GROUP_0
==> default: --- Resource Pool   : /
==> default: ---  --- Guest Summary ---
==> default: --- VM Name         : vm-vagrantTesting
==> default: --- Clone from VM   : vm-template
==> default: --- Memsize (MB)    : 4096
==> default: --- CPUS            : 4
==> default: --- Disk Type       : thick
==> default: --- Storage (GB)    : [{:size=>10, :datastore=>"RAID_GROUP_0"}, {:size=>10, :datastore=>"RAID_GROUP_0"}, {:size=>10, :datastore=>"RAID_GROUP_0"}, {:size=>10, :datastore=>"RAID_GROUP_0"}, {:size=>10, :datastore=>"RAID_GROUP_0"}, {:size=>10, :datastore=>"RAID_GROUP_0"}]
==> default: --- Guest OS type   : centos8-64
==> default: --- Autostart       : true
==> default: --- Allow Overwrite : True
==> default: ---   --- Guest Build ---
Opening VI source: vi://root@esxi:443/vm-template
Opening VI target: vi://root@esxi:443/
Deploying to VI: vi://root@esxi:443/
Transfer Completed
Completed successfully
==> default: --- VMID            : 1198
store[:size] : 10
store_size: 10
==> default: --- Creating Storage: disk_0.vmdk (10GB)
store[:size] : 10
store_size: 10
==> default: --- Creating Storage: disk_1.vmdk (10GB)
store[:size] : 10
store_size: 10
==> default: --- Creating Storage: disk_2.vmdk (10GB)
store[:size] : 10
store_size: 10
==> default: --- Creating Storage: disk_3.vmdk (10GB)
store[:size] : 10
store_size: 10
==> default: --- Creating Storage: disk_4.vmdk (10GB)
store[:size] : 10
store_size: 10
==> default: --- Creating Storage: disk_5.vmdk (10GB)
cmd: vim-cmd hostsvc/autostartmanager/update_autostartentry 1198 PowerOn 120 1 systemDefault 120 systemDefault
==> default: --- VM has been Powered On...
==> default: --- Waiting for state "running"
==> default: --- Success, state is now "running"
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

**Comment by josenk** [comment]
There is not enough details here to debug it...   You would have to try to re-create the problem - with debugging enabled.

> https://github.com/josenk/vagrant-vmware-esxi/wiki/Debugging-the-plugin

**Comment by SLongofono** [comment]
hmm, that didn't seem to give much additional information.  I got one additional line:

```
num adapters: 3,  vm.network.count: 0
```

**Comment by josenk** [comment]
Your not giving much to work with....  what debug options are you using?  You'll need to post what you are trying to do. 
Post your Vagrantfile also.

**Comment by SLongofono** [comment]
I am trying to automate creation of vms using esxi v7.  I have a template VM running CentOS 8, with a minimal installation plus headless access tools, security tools, and open-vmware-tools installed.  The template has 3 nics, which are active but not configured to connect automatically.

Following the provide example, I used the vagrant file below.  I ran it with the vagrant debug and didn't see any error messages.  I also ran it with the default esxi debug as you suggested.

It seems like the vm creation part is working as intended - the vm gets created and powered on, and I can see it has booted properly through the esxi web interface.  But either vagrant or the plugin is intermittently hanging on the last step "==> default: --- Waiting for state "running"", and if it resolves, I see the error message in the title.

Vagrant file:

```
_nodes = {
    'vm-vagrantTesting'    => [ ['Network1','Network2','Network3'],    [10,10,10,10,10,10],        ['IP1','IP2','IP3']    ],
}

# Common settings
_esxihost = 'esxiIP'
_box = 'generic/centos8'
_nvcpus = '4'
_ram_mb = '4096'

Vagrant.configure('2') do |config|
  _nodes.each do |(_name, _cfg)|

    # Unpack configuration parameters
    _networks, _disks, _IPs = _cfg
    _IP1, _IP2, _IP3 = _IPs

    config.vm.define _name do |machine|

      # General VM settings
      machine.vm.box = _box
      machine.vm.hostname = _name
      machine.vm.synced_folder('.','/vagrant',type:'rsync')

      # ESXI VM settings
      machine.vm.provider :vmware_esxi do |esxi|
        esxi.esxi_hostname = _esxihost
        esxi.esxi_username = 'root'
        esxi.esxi_password = 'prompt:'
        esxi.esxi_virtual_network = _networks
        esxi.clone_from_vm = 'vm-template'
        esxi.esxi_disk_store = 'RAID_GROUP_0'
        esxi.guest_numvcpus = _nvcpus
        esxi.guest_memsize = _ram_mb
        esxi.guest_disk_type = 'thick'
        esxi.guest_storage = _disks
        esxi.guest_autostart = 'true'
        esxi.local_allow_overwrite = 'true'
        esxi.debug = 'true'
      end

      # Network configuration
      machine.vm.provision 'shell',
        path: 'networkConfig.sh',
        env: {
          "IP1" => _IP1,
          "IP2" => _IP2,
          "IP3" => _IP3,
        }

    end    #machine
  end #nodes
end #vagrant
```

**Comment by SLongofono** [comment]
After digging a little deeper with vagrant debug, it seems that the networking is not exactly working as intended when cloning from an existing vm.  I changed to using the vagrant box minimal/centos8 instead, and had similar issues during the setting hostname step.  I decided on cloning in the first place to simplify the network interfaces setup, but if you have a way of assigning nics to specific virtual networks that would also work.

Am I interpreting your implementation correctly that you enumerate all the available esxi virtual networks, and apply IP settings in the same order blindly?  If so, how are they ordered? If not, how are you mapping calls to config.vm.network to interfaces and virtual networks?

**Comment by josenk** [comment]
You say your changing the hostname, but are you somehow trying to change the ip address when the system boots?  I suggest you look at the wiki about it 

I don't create a network interface order any more than Asus motherboards do...    If you have 3 physical nics in a physical motherboard it's the is os that determines the order, not the motherboard or nic manufacturer.  The same is true in the virtual world.

**Comment by SLongofono** [comment]
> You say your changing the hostname, but are you somehow trying to change the ip address when the system boots? I suggest you look at the wiki about it

I'm changing the hostname to the node name in the vagrant file.  I mentioned this because this is the step where things appear to go wrong.  That said, I _do_ want to change IP addresses to be static, on the second and third virtual networks.

> I don't create a network interface order any more than Asus motherboards do... If you have 3 physical nics in a physical motherboard it's the is os that determines the order, not the motherboard or nic manufacturer. The same is true in the virtual world.

I'm not sure I understand your explanation here.  When I set `esxi_virtual_network` using a list of network names, how do you map these to the NICs on the virtual machine?

Maybe my questions would be clearer if they were more general: What is supposed to happen when esxi_virtual_network is set?  If a list is passed, which networks get assigned to which interface?

And a followup question: Has esxi_virtual_network been tested in combination with setting a static IP on non-primary interfaces using a call to vm.network?

**Comment by josenk** [comment]
> When I set esxi_virtual_network using a list of network names, how do you map these to the NICs on the virtual machine?
 The virtual nics are added in order.  You can hardcode a MAC address and review the vmx file to see exactly how it's done.   BUT, as I explained...   Just because they are in order in the configuration (vms) file, doesn't mean the OS will detect them in that order!  I've seen where the OS detects the Intel nics first, even when they are added at the end of the list.  

> Has esxi_virtual_network been tested in combination with setting a static IP on non-primary interfaces using a call to vm.network?
This is a provider, not a provisioner, so really, this plugin has nothing to do with it.   But, I can tell you that setting the IP on the secondary interfaces will not interfere with Vagrant's communications to the guest while it's building, so it should be OK.

**Comment by SLongofono** [comment]
Thanks for the help. NICs detection order seems to be the problem.  Closing since it isn't relevant to the plugin.
