### ISSUE TITLE
Error: OVF Package is not supported by target Unsupported hardware family 'vmx-19'

### ISSUE THREAD

**Issue by rgl** [josenk/vagrant-vmware-esxi#121]
I'm lost with this error:

```console
rgl@rgl-desktop:~/Projects/esxi-vagrant/example$ vagrant up --provider=vmware_esxi --no-destroy-on-error
Bringing machine 'esxi' up with 'vmware_esxi' provider...
==> esxi: Virtual Machine will be built.
VMware ovftool 4.4.0 (build-15722219)
Opening VI source: vi://root@esxi.test:443/template-esxi-7.0.2-amd64-esxi
Opening VMX target: /tmp/d20210925-129159-fle9wz
Error: OVF Package is not supported by target:
 - Line 26: Unsupported hardware family 'vmx-19'.
Completed with errors
There was an OVF Tool error.
  Unable to access template-esxi-7.0.2-amd64-esxi
```

The same base vm/clone works fine with the [terraform provider](https://github.com/josenk/terraform-provider-esxi).

My vagrant provider block is alike:

```ruby
  config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = ENV['ESXI_HOSTNAME']
    esxi.esxi_username = ENV['ESXI_USERNAME']
    esxi.esxi_password = ENV['ESXI_PASSWORD']
    esxi.esxi_virtual_network = [ENV['ESXI_NETWORK']]
    esxi.clone_from_vm = ENV['ESXI_TEMPLATE']
    esxi.guest_storage = [{size: DATASTORE_DISK_SIZE_GB, datastore: ENV['ESXI_DATASTORE']}]
    esxi.guest_numvcpus = 4
    esxi.guest_memsize = 4*1024
    esxi.debug = 'true'
  end
```

Do you have any clue why this is happening?

Or how can I troubleshoot this (using `vagrant --debug` did not help nor did the `ovftool.log` contained any error)?

**Comment by josenk** [comment]
It's a bit weird.  I have not seen that error before.   It looks like this is the step that is using Ovftool to copy the config locally.  Is that template just a naming convention, or is it a real vSphere template?

You might have to enable vagrant debugging to get the Ovftool command that it's running, then run that command manually to see what's going on.

**Comment by rgl** [comment]
The `template-` prefix its just a convention of mine. This is using the ESXi free edition.

I've modified the vmx property from `virtualhw.version = "19"` to `virtualhw.version = "18"` and the `ovftool` now can create the VM, but when it starts, it crashes in a purple screen.

I also tried to upgrade from `VMware ovftool 4.4.0 (build-15722219)` to `VMware ovftool 4.4.1 (build-16812187)`, same result.

Next try, re-create the template with `vmx-18` :-(

**Comment by rgl** [comment]
It seems the most significant difference between a VM started with vagrant and the other with terraform is:

```diff
-guestOS = "other"
+guestOS = "vmkernel7"
```

For some reason, when started from vagrant, the `guest_guestos` property in ESXi is always set to `other` and that is why the machine purple screens. If I manually edit the VM using the ESXi UI, it works fine.

This is what I'm using in my Vagrantfile:

```ruby
  config.vm.provider :vmware_esxi do |esxi|
    esxi.guest_guestos = 'vmkernel7'
  end
```

Here are the full vmx files:

* The bad one, created with vagrant: [esxi.bad.vmx.txt](https://github.com/josenk/vagrant-vmware-esxi/files/7232064/esxi.bad.vmx.txt)
* The good one, created with terraform: [esxi.good.vmx.txt](https://github.com/josenk/vagrant-vmware-esxi/files/7232063/esxi.good.vmx.txt)

Am I missing something in my Vagrantile?

For reference, here's the full provider part:

```ruby
  config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = ENV['ESXI_HOSTNAME']
    esxi.esxi_username = ENV['ESXI_USERNAME']
    esxi.esxi_password = ENV['ESXI_PASSWORD']
    esxi.esxi_virtual_network = [ENV['ESXI_NETWORK']]
    esxi.clone_from_vm = ENV['ESXI_TEMPLATE']
    esxi.guest_storage = [{size: DATASTORE_DISK_SIZE_GB, datastore: ENV['ESXI_DATASTORE']}]
    esxi.guest_numvcpus = 4
    esxi.guest_memsize = 4*1024
    esxi.guest_guestos = 'vmkernel7'
    esxi.debug = 'true'
  end
```

**Comment by josenk** [comment]
I noticed this when I tried...

```
==> default: --- WARNING         : GuestOS:  not supported, using box/ovftool defaults
```

Looks like vmkernel7 needs to be added to the supported OS list...
>https://github.com/josenk/vagrant-vmware-esxi/blob/e3ba1f74d08a63e513d3ad2c7a4272f24d9030de/lib/vagrant-vmware-esxi/config.rb#L233-L236

In the mean time, you might want to try one the generic 'vmkernel'.

**Comment by rgl** [comment]
Thank You! Its now working! :-)

It no longer purple screens with `vmkernel`. I'm not sure this is a generic name, as it shows up as `ESXi 4.x` in the UI; anyways it works; even with `vmkernel65`.

Maybe vagrant-libvirt should not modify the guest-os field when we do not set (or its `nil`) `guest_guestos`?

**Comment by josenk** [comment]
99.99% of the time, you don't need to have exactly the correct guestos type.   Usually, a quick work-around can be done using an alternate.    You might have a point about not modifying the guest-os field...   I'll look into it if it becomes more problematic.

Closing this since vmkernel7 has been added.
