### ISSUE TITLE
VMware ESXi 7 guestOS types

### ISSUE THREAD

**Issue by seventhsite** [josenk/vagrant-vmware-esxi#124]
Where I can find ESXi 7.0.2 guestOS types? 

I have in config:

`   esxi.guest_guestos = 'debian11-64'`

But I get

`==> default: --- WARNING         : GuestOS:  not supported, using box/ovftool defaults`

and my cloned VM in ESXi show "Other (32-bit)"

**Comment by josenk** [comment]
I will need to add it to the next release...   It's not in the list.
> https://github.com/josenk/vagrant-vmware-esxi/blob/master/lib/vagrant-vmware-esxi/config.rb#L142-L155
