### ISSUE TITLE
==> default: --- Disk Store      : SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by raymondbutler** [josenk/vagrant-vmware-esxi#13]
Vargrant Version: 2.0.1
plugin version: vagrant-vmware-esxi (1.5.0)

==> default: Virtual Machine will be built.
==> default: --- WARNING         : Disk Store "vms-noc-01-local-storage-1" not found, using SyntaxError: invalid syntax
==> default: --- 
==> default: --- ESXi host       : 192.168.254.26
==> default: --- VM Name         : V-pvr-noc-05-root-TEST_VM
==> default: --- Box             : generic/centos7
==> default: --- Box Ver         : 1.3.40
==> default: --- Disk Store      : SyntaxError: invalid syntax
==> default: --- CPUS            : 2
==> default: --- Memsize (MB)    : 2048
==> default: --- Guest OS type   : centos-64
==> default: --- Virtual Network : ["NOC"]
==> default: --- Nic Type        : e1000
==> default: --- Resource Pool   : 
VMware ovftool 4.2.0 (build-5965791)
Opening VMX source: /root/.vagrant.d/boxes/generic-VAGRANTSLASH-centos7/1.3.40/vmware_desktop/ZZZZ_V-root-TEST_VM.vmx
Opening VI target: vi://root@192.168.254.26:443/
Error: Invalid target datastore specified (SyntaxError: invalid syntax): Possible completions: 
  vms-noc-01-local-storage-1 
Completed with errors
There was an OVF Tool error.

esxi.vm_disk_store = "vms-noc-01-local-storage-1"

Is this a bug or am I missing something?

**Comment by josenk** [comment]
That isn't normal...   "SyntaxError: invalid syntax" is getting passed back from the ESXi shell...   I would like you to try again with debugging enabled and the output of a few commands on the ESXi host.


1) Enable debug by adding this line to the provider section of the Vagrantfile.
```
      esxi.debug = `true`
```

2) Also, please ssh to your esxi server and send me the output of these commands.
```
# vmware --version
# df | grep "^[VMFS|NFS]" | sort -nk4 |sed "s|.*/vmfs/volumes/||g"|tail +2
# df
# vim-cmd hostsvc/summary/fsvolume
```

You can send it directly to my email address if you fell more secure with that...
    Jonathan S
    vagrant-vmware-esxi@jintegrate.co

**Comment by raymondbutler** [comment]
Hi,
Thanks for the reply, after digging I noticed what createvm.rb was doing and see the df command so I did run it on the ESX box and I got an error..

```
~ # df -h
Traceback (most recent call last):
  File "/bin/df", line 101, in <module>
    sys.exit(main(sys.argv))
  File "/bin/df", line 55, in main
    o = eval(output)
  File "<string>", line 1
    Errors: 
          ^
SyntaxError: invalid syntax
```
Which explains the error, I will investigate the issue with the esxi5.5 box and confirm that this was the issue all along.
Cheers 
Ray

**Comment by raymondbutler** [comment]
VMware ESXi 5.5.0 build-1331820

Last command results.
```vms-01-local-storage-1   VmfsVolume   VMFS      /vmfs/volumes/54955265-671fab0e-18d9-0015285d137c   naa.6b083fe0b25b7a001c470cf70632dd00:1   5999264006144   readWrite
                             VfatVolume   other     /vmfs/volumes/8520e3e1-58e4e26f-5ca2-b503172c716a                                                261853184   readOnly 
                             VfatVolume   other     /vmfs/volumes/b29d51e1-d91a3951-dec8-754d04c08efe                                                261853184   readOnly 
                             VfatVolume   other     /vmfs/volumes/54b3c950-8ea83306-568b-0015273d137c                                                299712512   readOnly```

**Comment by josenk** [comment]
I don't think there's much I can do if the df command on your esxi box doesn't work...  Yes, please investigate why it's not working and update this thread...

BTW:  There's a few google hits with the problem you describe.   'esxi 5.5 df invalid syntax'   You may have a bad disk.

**Comment by raymondbutler** [comment]
Hi Jonathan,
I have tested and all is well, I will close this issue.
