### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

### ISSUE THREAD

**Issue by r0k5t4r** [josenk/vagrant-vmware-esxi#130]
Hi,

I'm running latest Vagrant 2.2.19 and also latest standlone ESXi 7.0.3.

I have a vagrant file

https://pastebin.com/aDxJV6q9

to deploy multiple machines. Sometimes the deployment works just fine and sometimes I see this error:

Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

I'm pretty sure that it is related to the multiple network interfaces. I ensured that I use the same VM Network for all NICS, just in case the NICS get mixed up and vagrant would lose the connectivity to the VM. But even this doesn't seem to help. I'm using:

`vagrant up --no-parallel`

> Completed successfully
> ==> compute01: --- Avail DS vols   : ["BOOTBANK2", "BOOTBANK1", "USB-DS", "LOCKER-6091dc6f-125af731-9604-6c3be51bde8c", "truenas_rust_01", "truenas_nvme_01", "odroidxu4-esx-nfs-01"]
> ==> compute01: --- Avail Networks  : ["9000MTU", "OpenStack Tunnel", "Ceph Backend", "VM Network", "vmk-iscsi", "Management Network", "OpenStack", "OpenStack Octavia", "OpenStack API"]
> ==> compute01: ---   --- ESXi Summary ---
> ==> compute01: --- ESXi host       : 192.168.2.10
> ==> compute01: --- Virtual Network : ["VM Network", "VM Network", "VM Network", "VM Network"]
> ==> compute01: --- Disk Store      : truenas_nvme_01
> ==> compute01: --- Resource Pool   : /
> ==> compute01: ---  --- Guest Summary ---
> ==> compute01: --- VM Name         : compute01.fritz.box
> ==> compute01: --- Clone from VM   : template-centos8stream
> ==> compute01: --- Memsize (MB)    : 4096
> ==> compute01: --- CPUS            : 2
> ==> compute01: --- Nic Type        : vmxnet3
> ==> compute01: --- Guest OS type   : centos-64
> ==> compute01: --- Allow Overwrite : True
> ==> compute01: ---   --- Guest Build ---
> ovftool command: ovftool --noSSLVerify --overwrite --powerOffTarget  --X:logLevel=info --X:logFile=C:/Users/olive/AppData/Local/Temp/d20220622-23816-zivka2/ovftool.log --acceptAllEulas -dm=thin  -ds="truenas_nvme_01" --name="compute01.fritz.box" "vi://root:******@192.168.2.10/template-centos8stream" vi://root:******@192.168.2.10/
> Opening VI source: vi://root@192.168.2.10:443/template-centos8stream
> Opening VI target: vi://root@192.168.2.10:443/
> Deploying to VI: vi://root@192.168.2.10:443/
> Transfer Completed
> Completed successfully
> ==> compute01: --- Keeping file    : C:/Users/olive/AppData/Local/Temp/d20220622-23816-zivka2/template-centos8stream/ZZZZ_compute01.fritz.box.vmx
> ==> compute01: --- VMID            : 818
> ==> compute01: --- Custom vmx      : Append vhv.enable = "TRUE"
> ==> compute01: --- VM has been Powered On...
> ip1 (pri): ip2 (alt):
> ==> compute01: --- Waiting for state "running"
> ip1 (pri): ip2 (alt):
> ip1 (pri): ip2 (alt):
> ip1 (pri): ip2 (alt):
> ip1 (pri): ip2 (alt):
> ip1 (pri): ip2 (alt):
> ip1 (pri): ip2 (alt):
> ip1 (pri):192.168.2.107 ip2 (alt):
> Using cached guest IP address
> Get local IP address for NFS. (pri)
> nfs_host_ip: 192.168.56.1
> ==> compute01: --- Success, state is now "running"
> num adapters: 4,  vm.network.count: 3
> ==> compute01: --- Configuring     : 0.0.0.0/255.0.0.0 on VM Network
> ==> compute01: --- Configuring     : 192.168.2.214/255.255.255.0 on VM Network
> ==> compute01: --- Configuring     : 192.168.45.214/255.255.255.0 on VM Network
> ip1 (pri):192.168.2.107 ip2 (alt):
> Guest-specific operations were attempted on a machine that is not
> ready for guest communication. This should not happen and a bug
> should be reported.

In can ping 192.168.2.107 just fine and I have verified that this IP is assigned to VM compute01:

> vagrant ssh compute01
> 
> RUBY_PLATFORM: x64-mingw32
> Testing esxi connectivity
> ==> compute01: --- ESXi version    : VMware ESXi 7.0.3 build-19898904
> ==> compute01:
> ip1 (pri):192.168.2.107 ip2 (alt):
> Using cached guest IP address
> Get local IP address for NFS. (pri)
> nfs_host_ip: 192.168.56.1
> Using cached guest IP address
> Using cached guest IP address
> Get local IP address for NFS. (pri)
> nfs_host_ip: 192.168.56.1
> Using cached guest IP address
> Using cached guest IP address
> Get local IP address for NFS. (pri)
> nfs_host_ip: 192.168.56.1
> Using cached guest IP address
> Using cached guest IP address
> Get local IP address for NFS. (pri)
> nfs_host_ip: 192.168.56.1
> Using cached guest IP address
> Using cached guest IP address
> 
> This system is built by the Bento project by Chef Software
> More information can be found at https://github.com/chef/bento
> Last login: Wed Jun 22 10:51:26 2022
> 

Best Regards,
Oliver

**Comment by josenk** [comment]
Are you trying to assign static ips?

**Comment by r0k5t4r** [comment]
Exactly. But not on the primary Interface.

Von meinem iPhone gesendet

**Comment by josenk** [comment]
That can still be problematic...  Have you considered using terraform?

**Comment by r0k5t4r** [comment]
Yes I also came to the conclusion that it might make more sense to look into terraform. It is just so strange because it was working just fine a few weeks ago. I might give it one more try this week.

Von meinem iPhone gesendet
