### ISSUE TITLE
Provider ignores loops and sequence

### ISSUE THREAD

**Issue by kaspars-vilde** [josenk/vagrant-vmware-esxi#133]
Provider ignores loops and sequence of Vagrantfile.  Building clusters with this provider is pointless, because it's doesn't wait till previous VMs are prepared, but runs everything in parallel. Didn't find anything about configuring the sequence that in this git repo, assume it's not supported.

**Comment by josenk** [comment]
You didn't provide an example, so pretty hard to comment...Maybe terraform will be a better fit for your use-case.

**Comment by kaspars-vilde** [comment]
Loop Over VM Definitions. Provider skips them entirely. It run VM provisioning  simultaneously, same for scripts. Run perfectly on Virtual Box and Vmware Workstation, so..
example:
(1..3).each do |i|
  config.vm.define "node-#{i}" do |node|
    node.vm.provision "shell",
      inline: "echo hello from node #{i}"
  end
end

**Comment by josenk** [comment]
Your example doesn't even have `vm.provider: vmware_esxi` specified...

Have you looked at the Multimachine example? 
> https://github.com/josenk/vagrant-vmware-esxi/blob/master/example_box/Vagrantfile-multimachine

Have you considered Terraform?   It might be a better fit for what you are trying to accomplish.

**Comment by kaspars-vilde** [comment]
This is not what i'm talking about. Multi machine just means there will be more than one vm provisioned and yes it just deploys them in paralel.

Snippet from my Vagrantfile. Vagrant doesn't give any errors, but provider just skips the loop entirely and deploy everything at the same time. If you cannot point to parameter, which forces to respect the sequence than just say the feature is unsupported

    (1..NUM_MASTER_NODES-1).each do |i|      
        config.vm.define "#{K8S_CL_NAME}-#{MASTER_SUFFIX}-#{i+1}" do |master|
            master.vm.box = VAGRANT_IMAGE_NAME
            master.vm.network "private_network", ip: K8S_NET + "#{i + MASTER_START_IP + 1}"
            master.vm.hostname = "#{K8S_CL_NAME}-#{MASTER_SUFFIX}-#{i+1}"
            master.vm.provider :vmware_esxi do |esxim|
                esxim.esxi_hostname         = '192.168.131.100'
                esxim.esxi_username         = 'root'
                esxim.esxi_password         = 'pass'
                esxim.esxi_virtual_network  = "VM Network"
                esxim.guest_numvcpus        = 2
                esxim.guest_memsize         = 2048
                esxim.local_allow_overwrite = 'True'
            end            
            master.vm.provision "shell", path: "scripts/prepare.sh"
            master.vm.provision "shell", path: "scripts/master.sh"
        end
    end

**Comment by jmcgnh** [comment]
It seems unfair to bash Jonathan for your misunderstandings. The
vagrantfile is processed in its entirety to produce a data structure,
before any VMs are instantiated. If you want a later VM to depend on
content of an earlier VM, you need to either prebuild the linking data
between them or you need two invocations (or more) of vagrant.

 -- jmcg

**Comment by josenk** [comment]
Well said Jim.  Thanks.

Looks like a provisioner problem to me...  Not my code.

It's correct that there is no mention of configuring the sequence of provisioners.   This is a provider, not a provisioner.  You may want to look at this.
> https://www.vagrantup.com/docs/provisioning/basic_usage
