### ISSUE TITLE
Is there option setup OS hostname?

### ISSUE THREAD

**Issue by devsecops-edu-vn** [josenk/vagrant-vmware-esxi#139]
Do we have same as it?

esxi.os_hostname = 'linux'

I have read below document but I could not find it

https://github.com/josenk/vagrant-vmware-esxi/wiki/Vagrantfile-example:-Single-Machine,-fully-documented

Thank you very much!

**Comment by josenk** [comment]
No, there is no option to set the os hostname.    This installs/configures a VM on your esxi host, it does not configure your OS.

Just like you are unable to configure the os hostname from the ui, you are not able to configure the os hostname using this this tool.
