### ISSUE TITLE
With only 1 virtual_network defined, unable to push static IPs

### ISSUE THREAD

**Issue by skorada-rvbd** [josenk/vagrant-vmware-esxi#14]
Hi,

I am trying to bring up a VM and give it a static IP

Vagrantfile

```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.forward_agent = true
  config.vm.define test-vm do |x|
    x.vm.box = "bento/ubuntu-16.04"
    x.vm.network "private_network", ip: "10.73.40.201"  ===> Desired static IP
    x.vm.provider :vmware_esxi do |v|
      v.esxi_hostname = '10.73.40.19'
      v.esxi_username = 'root'
      v.esxi_password = 'secret'
      v.custom_vmx_settings = [['vhv.enable', 'TRUE']]
      v.vmname = test-vm
      v.memsize = 6000
      v.numvcpus = 2
      v.virtual_network = ["VM Network"]  ===> 1 virtual network defined
      v.debug = 'true'
      v.allow_overwrite = 'True'
    end
  end
end
```

When I do a vagrant up and then log in to the VM , I see that the IP assigned to it is via dhcp

Console logs
```
Bringing machine 'test-vm' up with 'vmware_esxi' provider...
==> test-vm: Virtual Machine will be built.
Available DS Volumes: ["datastore1"]
Available Networks: ["VM Network", "Management Network"]
guestvm_network[0]: VM Network
==> test-vm: ---
==> test-vm: --- ESXi host       : 10.73.40.19
==> test-vm: --- VM Name         : test-vm
==> test-vm: --- Box             : bento/ubuntu-16.04
==> test-vm: --- Box Ver         : 201801.02.0
==> test-vm: --- Disk Store      : datastore1
==> test-vm: --- CPUS            : 2
==> test-vm: --- Memsize (MB)    : 6000
==> test-vm: --- Guest OS type   : ubuntu-64
==> test-vm: --- Virtual Network : ["VM Network"]
==> test-vm: --- Allow Overwrite : True
==> test-vm: --- Resource Pool   :
VMware ovftool 4.2.0 (build-5965791)
ovftool command: ovftool --noSSLVerify --overwrite --powerOffTarget  --net:"net0=VM Network" -dm=thin  -ds="datastore1" --name="test-vm" "/home/username/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-16.04/201801.02.0/vmware_desktop/ZZZZ_test-vm.vmx" vi://root:******@10.73.40.19
Opening VMX source: /home/username/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-16.04/201801.02.0/vmware_desktop/ZZZZ_test-vm.vmx
Enter login information for target vi://10.73.40.19/
Username: root
Password: **********
Enter login information for target vi://10.73.40.19/
Username: root
Password: **********
Opening VI target: vi://root@10.73.40.19:443/
Deploying to VI: vi://root@10.73.40.19:443/
Transfer Completed
Completed successfully
Keeping file: /home/username/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-16.04/201801.02.0/vmware_desktop/ZZZZ_test-vm.vmx
==> test-vm: --- VMID: 86
==> test-vm: --- Custom vmx      : Append vhv.enable = "TRUE"
==> test-vm: --- VM has been Powered On...
==> test-vm: --- Waiting for state "running"
==> test-vm: --- Success, state is now "running"
num adapters: 1,  vm.network.count: 1
    test-vm:
    test-vm: Vagrant insecure key detected. Vagrant will automatically replace
    test-vm: this with a newly generated keypair for better security.
    test-vm:
    test-vm: Inserting generated public key within guest...
    test-vm: Removing insecure key from the guest if it's present...
    test-vm: Key inserted! Disconnecting and reconnecting using new SSH key...
==> test-vm: Rsyncing folder: /home/username/ => /vagrant
```

Now I assumed that the VM would have its IP 10.73.40.201 instead I see that it has 10.73.40.50

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:93:e1:f5 brd ff:ff:ff:ff:ff:ff
    inet 10.73.40.50/23 brd 10.73.41.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe93:e1f5/64 scope link
       valid_lft forever preferred_lft forever
```

Is it a mandate to define multiple virtual networks ?

Thanks,
Shashank

**Comment by josenk** [comment]
Vagrant doesn't configure the first network interface.  That is considered the management network.   Here is a thread using the libvirt provider.

https://github.com/vagrant-libvirt/vagrant-libvirt/issues/613
and here: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/409

The Vagrant documentation doesn't explain it very well, but the management network (first nic) is not configurable...  I already support setting a fixed MAC address to all interfaces.  You just need to set a fixed IP for the MAC on your DHCP server.

However, I did research this a bit more....   It looks like the expected result is to create a new virtual network interface when a vm.network is specified.   Currently I don't create new esxi.virtual_network entries automatcially...  

  I'll change vagrant-vmware-esxi default behaviour to create a new esxi.virtual_network entry to match the defaults from other providers.    *** I don't really like choosing the first esxi virtual_network found, but that's the only solution I have.  ***

**Comment by skorada-rvbd** [comment]
Thanks Jonathan

```
I already support setting a fixed MAC address to all interfaces. You just need to set a fixed IP for the MAC on your DHCP server.
```
A little confused here, how do I achieve the above using the Vagrantfile?

Since you mentioned that the first network given would be considered as the management network I tried to define the networks as the following

`v.virtual_network = ["Management Network", "VM Network"]` but that throws an error

```
Bringing machine 'test-vm' up with 'vmware_esxi' provider...
==> test-vm: Virtual Machine will be built.
Available DS Volumes: ["datastore1"]
Available Networks: ["VM Network", "Management Network"]
guestvm_network[0]: Management Network
guestvm_network[1]: VM Network
==> test-vm: ---
==> test-vm: --- ESXi host       : 10.73.40.19
==> test-vm: --- VM Name         : test-vm
==> test-vm: --- Box             : bento/ubuntu-16.04
==> test-vm: --- Box Ver         : 201801.02.0
==> test-vm: --- Disk Store      : datastore1
==> test-vm: --- CPUS            : 2
==> test-vm: --- Memsize (MB)    : 6000
==> test-vm: --- Guest OS type   : ubuntu-64
==> test-vm: --- Virtual Network : ["Management Network", "VM Network"]
==> test-vm: --- Allow Overwrite : True
==> test-vm: --- Resource Pool   :
VMware ovftool 4.2.0 (build-5965791)
ovftool command: ovftool --noSSLVerify --overwrite --powerOffTarget  --net:"net0=Management Network" --net:"net1=VM Network" -dm=thin  -ds="datastore1" --name="test-vm" "/home/username/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-16.04/201801.02.0/vmware_desktop/ZZZZ_test-vm.vmx" vi://root:******@10.73.40.19
Opening VMX source: /home/username/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-16.04/201801.02.0/vmware_desktop/ZZZZ_test-vm.vmx
Enter login information for target vi://10.73.40.19/
Username: root
Password: **********
Opening VI target: vi://root@10.73.40.19:443/
Error: Invalid target name (Management Network) specified in net mapping. OVF networks:   net0  net1. Target networks:   VM Network
Completed with errors
There was an OVF Tool error.
```

Am I still using it wrong?

**Comment by josenk** [comment]
You are doing it wrong....   The first interface is VAGRANT's management network.   Not ESXi.   You cannot configure a static IP on the first network interface because ---> Vagrant doesn't want you to. <---  This question exists for Vagrant regardless of Provider.

I offer two possible solutions to your problem...   

1)    The closest way to configure a static IP on the first interface is to set a MAC address and then configure your DHCP server to map a static IP to that MAC address.

```
     v.virtual_network = ["VM Network"]
     v.mac_address = ["00:50:56:00:41:41"]
```

2)  OR, If you don't mind having two interfaces.  You can assign a static IP to the SECOND interface. 

```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.forward_agent = true
  config.vm.define test-vm do |x|
    x.vm.box = "bento/ubuntu-16.04"
    x.vm.network "private_network", ip: "10.73.40.201"  #===> Desired static IP for interface 2
    x.vm.provider :vmware_esxi do |v|
      v.esxi_hostname = '10.73.40.19'
      v.esxi_username = 'root'
      v.esxi_password = 'secret'
      v.custom_vmx_settings = [['vhv.enable', 'TRUE']]
      v.vmname = test-vm
      v.memsize = 6000
      v.numvcpus = 2
      v.virtual_network = ["VM Network","VM Network"]  #===> 2 virtual network defined
      v.debug = 'true'
      v.allow_overwrite = 'True'
    end
  end
end
```

**Comment by skorada-rvbd** [comment]
Thanks Jonathan.

Assigning a static IP to the second interface was what I had wanted, but since the plugin doesnt create a new virtual network interface I cant access the VM over that interface. Am I correct in understanding it?

For eg. my host machine and esxi server were on 10.73.40.1 network and I bring up VM on the esxi server with some ip (public or private)
` x.vm.network "public_network", ip: "10.10.10.10" `
 I cant access the VM on 10.10.10.10 as the virtual network isnt created.

**Comment by josenk** [comment]
vagrant-vmware-esxi will not create a new virtual network on the esxi host...   You need to create your esxi virtual networks manually using vSphere console or web gui.   It's impossible for the plugin to know the technical details to create it for you.  (which nic to use, which subnet, etc...)

libvirt is able to create a virtual network on your local host because the traffic is not routed outside your host....

BTW:  The example I gave you above...  You can re-use the existing esxi virtual network for a second interface on your guest.   In your original post, I see an IP from the ifconfig, eth0 is "10.73.40.50/23"

IP 10.10.10.10 is not valid...   
>http://jodies.de/ipcalc?host=10.73.40.50&mask1=23&mask2=

You need to select and IP from the valid IP range 10.73.40.1 - 10.73.41.254

**Comment by skorada-rvbd** [comment]
Thanks Jonathan.
This was really helpful for me 👍
