### ISSUE TITLE
ssh-config HostName/IP changes post running a provisioning script

### ISSUE THREAD

**Issue by skorada-rvbd** [josenk/vagrant-vmware-esxi#15]
Hi Jonathan,

Need some info on this issue that I have been facing. I am not entirely sure if its a plugin issue but I dont see it happening when I run the same tests on libvirt.

Vagrantfile:

```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.forward_agent = true
  config.vm.define test-vm do |x|
    x.vm.box = "bento/ubuntu-16.04"
    x.vm.provider :vmware_esxi do |v|
      v.esxi_hostname = '10.xx.xx.19'
      v.esxi_username = 'root'
      v.esxi_password = 'secret'
      v.custom_vmx_settings = [['vhv.enable', 'TRUE']]
      v.vmname = test-vm
      v.memsize = 6000
      v.numvcpus = 2
      v.debug = 'true'
      v.allow_overwrite = 'True'
    end
  end
end
```

Prior to the script that runs, following is the out of vagrant ssh-config

```
==> test-vm: --- ESXi version    : VMware ESXi 6.5.0 build-4887370
Host test-vm
HostName 10.xx.xx.xx   ====> The hostname 
User vagrant
Port 22
UserKnownHostsFile /dev/null
StrictHostKeyChecking no
PasswordAuthentication no
IdentityFile /home/username/.vagrant.d/insecure_private_key
IdentitiesOnly yes
LogLevel FATAL
ForwardAgent yes
With this when I run vagrant ssh it does a ssh to the VM without being prompted for a password
```

I can directly access the vm running `vagrant ssh`

```
==> test-vm: --- ESXi version    : VMware ESXi 6.5.0 build-4887370
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-87-generic x86_64)

* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.

vagrant@vagrant:~$   ===> PASSWORDLESS SSH
```

Now I modify the vagrant file to include a shell script that provisions my VM after it comes up.
The script does a couple of stuff, like creates some bridge network interfaces and installs some packages etc.

I modify my Vagrant file to include the following

```
x.vm.provision :shell do |s|
       s.path = /home/username/test.sh
    end
```

Post the script, vagrant ssh-config.

```
Host test-vm
HostName 172.18.0.1 ===> CHANGED
User vagrant
Port 22
UserKnownHostsFile /dev/null
StrictHostKeyChecking no
PasswordAuthentication no
IdentityFile /home/username/.vagrant.d/insecure_private_key
IdentitiesOnly yes
LogLevel FATAL
ForwardAgent yes
Why does vagrant change the hostname. Due to this I am unable to do a passwordless ssh to the VM using 'vagrant ssh'
```

Now when I try to run a vagrant ssh, it asks for a password.

```
vagrant ssh
vagrant@172.18.0.1's password:  ====> PASSWORD PROMPT
```

I have tried the same test with libvirt and I dont run into this.
Why does the IP in the ssh-config change?

Regards

**Comment by skorada-rvbd** [comment]
Basically what I am trying achieve is fetching the ip address of the interface eth0 post the VM provisioning is complete through my script. So tried doing a vagrant ssh. If there's another solution to do this without ssh that would work for me too. I tried looking up .vagrant folder and check if there is any info about the machine IPs but that was not of much help

**Comment by josenk** [comment]
Not much I can do here...   I have no idea what your script is doing.   Sounds like a networking issue.

Why does the IP in ssh-config change?   Most likely it's caused by your script.
   ssh-config gets its IP from esxi (via open-vm-tools / VMware tools).    I'm sure if you monitor the VM in vSphere, you'll see ip's change there too.   open-vm-tools/vmware tools is probably confused with your network changes.   Login to your VM through the console and debug it from there.

BTW:  Are you 100% sure you're logging into your guest on 172.18.0.1???    Shutdown that vm, then try to ping or ssh to that IP to see if some other server is running with that IP.

**Comment by skorada-rvbd** [comment]
I couldnt figure why this was happening. Maybe something my script is doing that causing the change. Closing the issue. Thanks Jonathan
