### ISSUE TITLE
Support for Windows VMs?

### ISSUE THREAD

**Issue by clong** [josenk/vagrant-vmware-esxi#18]
Hello,

While using this as a provider for a Windows VM, I get the following:
```
==> dc: Pruning invalid NFS exports. Administrator privileges will be required...
==> dc: Exporting NFS shared folders...
==> dc: Preparing to edit /etc/exports. Administrator privileges will be required...
==> dc: Mounting NFS shared folders...
Vagrant attempted to execute the capability 'mount_nfs_folder'
on the detect guest OS 'windows', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

Is it possible to launch a Windows VM and sync folders with anything other than NFS at this time?

**Comment by josenk** [comment]
What you are attempting to do works with other providers???

**Comment by clong** [comment]
I'm not sure if I understand your question. I am able to provision this same VM using Virtualbox/VMware Fusion if that's what you are asking.  I think am I just asking if there is a way to sync folders other than nfs using this plugin.

**Comment by josenk** [comment]
I've tested my plugin with NFS and rsync.  But it's pretty difficult to test every combination of client system (your PC/mac) and guests....   If you want me to help debug this, I would need to know a bit more details.   Like what is your client system? What version of vagrant/plugin are you using, what guest are you building.   A minimalist Vagrantfile that can reproduce the problem could help.

**Comment by clong** [comment]
Sure and I completely understand - I was just wondering if you knew of a solution that would allow me to use this plugin with ESXI guests -- if no solution exists that is okay too :)

OS: MacOS 10.12.6
Vagrant: 2.0.1
Plugin version: vagrant-vmware-esxi (2.0.2)

The box I'm trying to use is essentially the Windows 2016 and Windows 10 packer builds listed in this repo: (https://github.com/StefanScherer/packer-windows). I used Packer to create the Windows box and then I am attempting to deploy it to ESXI using this plugin, but since the guest OS is Windows, it doesn't support using NFS or rsync for folder sync.

**Comment by josenk** [comment]
Hmmmm,   I don't have a Mac to test as a client...   Also, I haven't done any testing with Windows guests.   I would say building Windows test environments is not something typically done with Vagrant.

   BTW:  The provisioning part is done by Vagrant, not the provider.   There is three variables the provider needs to populate and Vagrant does the rest....

Have you tried SMB?   It seems it's supported using a MAC client (host).
https://www.vagrantup.com/docs/synced-folders/smb.html

**Comment by clong** [comment]
Good idea, I'll try that out this week.

**Comment by josenk** [comment]
abandoned
