### ISSUE TITLE
Add linked_clone support

### ISSUE THREAD

**Issue by rgl** [josenk/vagrant-vmware-esxi#19]
It would be really nice to support `linked_clone` as it greatly shortens the deployment time.

```ruby
config.vm.provider 'vmware_esxi' do |esxi|
  esxi.linked_clone = true
...
```

**Comment by josenk** [comment]
I wont be able to implement linked clones like Virtualbox or VMware Workstation pro/Fusion pro.   ESXi just doesn't support linked clones.  

1) There are some hacks out there to have a snapshot pointing to a shared source vmdk.   That is just asking for trouble!   Too many pieces that could break everything.  (Deleting the source, snapshots, modifying vmdk files....)
2) Full clones could be done using Templates. That would be nice, but ESXi doesn't have templates.   That is a vCenter function.
3) The ovftool can create a full clone from a vm on the ESXi server.  I'll look into it, but it might be a big task to implement something like that...   Also, Vagrant manages the local boxes.   That functionality would be lost.

**Comment by rgl** [comment]
I see, no problem at all, it really seems too troublesome to implement! please disregard my request.

PS I'm still trying to wrap my head around of what a standalone esxi can really do, but it seems all the good stuff (like templates and linked clones) is only available in vSphere.

**Comment by josenk** [comment]
There is a lot of really cool stuff with vCenter!  But you have to pay for it...     DR, vmotion, storage vmotion, advanced networking, advanced storage, etc...

   A standalone esxi server will have one of the best hypervisors, but it's missing all the cool tools around it.   It's free.

There are lots of great articles about the differences.
