### ISSUE TITLE
vagrant up hangs "waiting for state running" when a box without VMWare Tools is Used

### ISSUE THREAD

**Issue by szmoore** [josenk/vagrant-vmware-esxi#2]
If the guest does not have VMWare Tools, the command used in [`read_ssh_info`](https://github.com/josenk/vagrant-vmware-esxi/blob/master/lib/vagrant-vmware-esxi/action/read_ssh_info.rb#L44)  is unable to get an IP address which causes the state to become stuck at `Powered On` because `read_ssh_info` always returns `nil` which gets checked [here](https://github.com/josenk/vagrant-vmware-esxi/blob/master/lib/vagrant-vmware-esxi/action/read_state.rb#L63).

Manually tested in SSH.

1. Without VMWare Tools (`centos/7`)
```
[root@localhost:~] vim-cmd vmsvc/get.guest 3 | grep ipAddress | head -n 1
   ipAddress = <unset>, 
```

2. With VMWare Tools [`mvermaes/centos7-vmware-tools`](https://app.vagrantup.com/mvermaes/boxes/centos7-vmware-tools)
```
[root@localhost:~] vim-cmd vmsvc/get.guest 7 | grep ipAddress | head -n 1
   ipAddress = "192.168.1.43", 
```

Should "use a box with VMWare Tools" be added to `README.md` ?

**Comment by josenk** [comment]
What's happening here is the plugin requires the IP address to access the VM.  Without open-vm-tools or vmware tools installed, the IP address is not given to the ESXI host (as you pointed out), the VM status will be "powered_on" and you cannot vagrant ssh or provision.

Unfortunatly, centos/7 doesn't have open-vm-tools or vmware tools installed.   If you really want to use a certain box, you could manually get the IP by loggin into the VM from the VMware console, install vmware tools, then repackage it.  You could also send a bug report the the box packager.  ;-)

When "vagrant up" boots the VM, it's waiting (not really hung) for open-vm-tools or vmware tools to start.   I'll update the code to provide a message that the VM did not transition to the "running" state.   In README.md it's documented under requirements, however I'll try to clarify it.

Thanks for the feedback.

**Comment by szmoore** [comment]
Thank you, I think a message in the code as you suggested would be helpful, I'm happy if you want to close the issue.
