### ISSUE TITLE
Can you pass custom values to the ovftool to further customize the VM

### ISSUE THREAD

**Issue by db-rdz** [josenk/vagrant-vmware-esxi#21]
I was wondering if there is a way to specify a custom gateway, dns, or ntp for the VM.

**Comment by josenk** [comment]
No, you cannot specify any network parameters to the ovftool.  The ovftool is not used to configure anything inside the VM.  (and neither is my plugin)
   https://www.vmware.com/support/developer/ovf/ovf420/ovftool-420-userguide.pdf

Vagrant itself has some very basic network configuration options. It can configure a static IP & netmask.   If you want to configure things like gateway, dns or ntp you'll have to script it yourself.
   https://www.vagrantup.com/docs/networking/private_network.html 
   https://www.vagrantup.com/docs/networking/public_network.html

Normally, you would specify network parameters on your DHCP server.
