### ISSUE TITLE
VM gets disconnected on creating bridge interface in provisioning script

### ISSUE THREAD

**Issue by skorada-rvbd** [josenk/vagrant-vmware-esxi#25]
Hi Jonathan,

I run a provisioning script post bringing up the VM using the plugin.
The script creates a bridge interface for the eth0 and migrates its IP to eth0_br, when this happens the provisioning script hangs and doesnt proceed further

I wanted to know if the plugin supports this behavior or whether plugin loses connectivity when IP is migrated. Looking for an idea.

**What is happening:**

_Interface before running the script:_
```
eth0      Link encap:Ethernet  HWaddr 00:0c:29:8d:70:50
          inet addr:10.xx.xx.xx  Bcast:10.73.41.255  Mask:255.255.254.0
          inet6 addr: fe80::20c:29ff:fe8d:7050/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:769139 errors:0 dropped:0 overruns:0 frame:0
          TX packets:328946 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1066226238 (1.0 GB)  TX bytes:23426075 (23.4 MB)
```

_Interface post the script:_ (hangs after creating the bridge)
```
eth0      Link encap:Ethernet  HWaddr 00:0c:29:8d:70:50
          inet6 addr: fe80::20c:29ff:fe8d:7050/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:769139 errors:0 dropped:0 overruns:0 frame:0
          TX packets:328946 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1066226238 (1.0 GB)  TX bytes:23426075 (23.4 MB)

eth0_br   Link encap:Ethernet  HWaddr 52:54:00:90:85:35
          inet addr:10.xx.xx.xx Bcast:10.73.41.255  Mask:255.255.254.0
          inet6 addr: fe80::5054:ff:fe90:8535/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4875 errors:0 dropped:0 overruns:0 frame:0
          TX packets:53 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:229964 (229.9 KB)  TX bytes:9218 (9.2 KB)
```

**Comment by josenk** [comment]
Sorry, Vagrant doesn't support modifying the primary interface.   Therefore, the provider doesn't support modifying the primary interface.


https://github.com/josenk/vagrant-vmware-esxi/wiki/How-to-configure-a-static-IP-on-the-primary-interface.

There is two things to try. 
  1) Do the configuration (update config files only), but do not make it live.  Then "vagrant reload". If it boots normally, that will be your work-around.
  2) Disable the VM's IP cache.  Use the Vagrantfile option:    esxi.local_use_ip_cache = 'False'

**Comment by skorada-rvbd** [comment]
Thanks Jonathan.
```
 Use the Vagrantfile option: esxi.local_use_ip_cache = 'False'
```
using the option helped solve my issue

How does it work though?

**Comment by josenk** [comment]
Vagrant constantly checks the IP address of the guest VM.   This steps is a bit slow because it needs to ssh to the esxi host each time.  

  The IP should normally NOT change, so I decided to cache that IP.  Subsequent checks for the guest VMs IP address, I just return the cached value.  If you disable the IP caching, your vagrant commands will be slower...

The preferred solution is to stage your network changes, then run "vagrant reload" to reboot the guest VM.

**Comment by skorada-rvbd** [comment]
Hi Jonathan

I am posting a follow up query for the above issue.
The esxi.local_use_ip_cache = 'False' worked wonderfully for me but I am sort of facing a similar issue with Libvirt Vagrant. Do you know of a similar option/config in the libvirt ? I looked around in the documentation but couldnt find any. Would be helpful if you could let me know if there is a similar "fix" in libvirt as well

Thanks

**Comment by josenk** [comment]
I'm sorry, I haven't worked that extensively with the libvirt plugin. 

  Saving the IP address is a bit of a hack to speed things up and that is why I put an option to disable it.   If they're doing the same, they should also have an option to disable it.  You may want to post an issue on their project.

   I get the IP address from the VMware tools.   I'm not even sure how libvirt is doing it???
