### ISSUE TITLE
gracefull shutdown and reload

### ISSUE THREAD

**Issue by as22323** [josenk/vagrant-vmware-esxi#28]
Within the same Vagrantfile, I'm looking to run one set of shell commands, reboot the vm then run a second set of shell commands. 
Example:
-----------------------------
```
config.vm.provision "shell", inline: <<- SHELL 
  echo "first block of commands"
  reboot
SHELL

config.vm.provision :reload
config.vm.provision "shell", inline: <<- SHELL 
  echo "second block of commands"
SHELL
```
-----------------------------

However, I get the following errors (only first set of commands ran. "shutdown -r" also did not work): 
-----------------------------
```
==> default: Running provisioner: reload... 
==> default --Starting graceful shutdown...
There was an error talking to ESXi. 
  Unable to shutdown the VM: 
    (vmodl.fault.SystemError) { 
    faultCause = (vmodl.MethodFault) null,
    reason = "Invalid fault", 
    msg = "Received SOAP response fault from [<cs: p: -------, TCP:localhost:80>]: shutdownGuest
vim.fault.genericVmConfigFault" 
```
-----------------------------

Is the following made to help with graceful shutdown [lib/vagrant-vmware-esxi/action/shutdown.rb]? If so, how can it be used in the Vagrantfile?

**Comment by josenk** [comment]
lib/vagrant-vmware-esxi/action/shutdown.rb is used for the "vagrant halt" command.  I never tested "config.vm.provision :reload" ...   I don't remember seeing that on vagrant web site???

You may want to use another method to reboot your vm.
