### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rgl** [josenk/vagrant-vmware-esxi#3]
I would like to try out your esxi vagrant plugin, but having a GPL licensed vagrant plugin is a no-go, because it would mean that any Vagrantfile would need to be GPL too. Why didn't you use MIT (like Vagrant itself) or LGPL?

**Comment by josenk** [comment]
In my opinion, MIT license is way too "free" for my taste...   I don't agree that I will do all the work, then someone can package it and call it their own.   If you require special features, you can fork it (keeping it GPL).   Or I'm willing to make a commercial (closed source) licence with (or without) special features.

I'm sorry, but my free to use version here on github will stay as GPL.

**Comment by rgl** [comment]
No one should repackage and call it their own, even with MIT.

My only concern is what is the license of my Vagranfile if I use this plugin, because it would have to directly use the plugin code to configure esxi.

BTW, I'm not even sure that you can mix MIT with GPL.

**Comment by josenk** [comment]
I really don't think you need to be concerned about your Vagrantfile.  

   1) The Vagrantfile is directly read by Vagrant, not by any plugin.
   2) The Vagrantfile is a list of YOUR personal configuration information and preferences.  It's not part of the code I distribute.  And it's certainly not something you would be re-distributing!
   3) I don't distribute a Vagrantfile, only an "example" on github.   "vagrant plugin install ..." doesn't install any Vagrant file, or template, or example.

In my opinion, the above points is enough that you don't need to consider your Vagrantfile GPL...
