### ISSUE TITLE
Wrong password used when creating Ansible inventory for hosts provisioned on different ESXi servers with different passwords

### ISSUE THREAD

**Issue by jbregman** [josenk/vagrant-vmware-esxi#33]
**Vagrant Version:**  2.0.1
**Plugin Version:** 2.2.1beta
**Client O/S:** Mac OSX 10.12.6

In my Vagrant file, I have some hosts that are configured to use one ESX1 server (server1), and some hosts that are configured to use another ESXi server (server2).

When the Ansible provisioner runs, I get an authentication error:

```
/opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.rb:250:in `start': Authentication failed for user root@192.168.10.4 (Net::SSH::AuthenticationFailed)
	from /Users/josh.bregman/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.2.1beta/lib/vagrant-vmware-esxi/action/read_state.rb:79:in `read_state'
	from /Users/josh.bregman/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.2.1beta/lib/vagrant-vmware-esxi/action/read_state.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/josh.bregman/.vagrant.d/gems/2.4.2/gems/vagrant-vmware-esxi-2.2.1beta/lib/vagrant-vmware-esxi/action/esxi_password.rb:18:in `call'
``` 

I added some debugging information and it looks like the issue is that there is a single global password stored in $esxi_password.

This passwords for server1 and server2 are different so this is likely why this is failing.

**Comment by josenk** [comment]
Yes, I believe you are right... The global variable will be used for both ESXi servers.  I have a single esxi server and never really thought people would do multimachines using more than one esxi host (with different passwords).  I never tested this configuration.   This should be fixable by storing the password differently.   I'll have a new beta for you shortly.
