### ISSUE TITLE
OVF Tool Error

### ISSUE THREAD

**Issue by brustabr** [josenk/vagrant-vmware-esxi#34]
Hello. When trying to deploy some ready-made vagrant boxes, the following error is appearing:

ERROR vagrant: /root/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-esxi-2.2.0/lib/vagrant-vmware-esxi/action/createvm.rb:516:in `createvm'
/root/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-esxi-2.2.0/lib/vagrant-vmware-esxi/action/createvm.rb:16:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/warden.rb:34:in `call'
/root/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-esxi-2.2.0/lib/vagrant-vmware-esxi/action/read_state.rb:64:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/warden.rb:34:in `call'
/root/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-esxi-2.2.0/lib/vagrant-vmware-esxi/action/esxi_password.rb:18:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine.rb:227:in `action_raw'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine.rb:202:in `block in action'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:592:in `lock'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine.rb:188:in `call'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine.rb:188:in `action'
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: There was an OVF Tool error.

My setup 
Vagrant 2.0.3 install on Debian 8, 64 bits (3.16.0-5-amd64)
Plugin vagrant-vmware-esxi
VMware ovftool 4.3.0 (build-7948156)

ESXi host:

6.0.0 (Build 2809209)
no resource_pool

**Comment by brustabr** [comment]
Could you help me?
Thank you

**Comment by josenk** [comment]
In your Vagrant file, you should enable debugging...  ovftool did not complete for some reason.

https://github.com/josenk/vagrant-vmware-esxi/wiki/Debugging-the-plugin

**Comment by brustabr** [comment]
Done. Our environment is controlled and I have verified that ovftool communicates over port 443 with the destination ESXI. Now it worked.  Nice plugin. Congratulations!

**Comment by josenk** [comment]
awesome.  Thanks for the feedback.
