### ISSUE TITLE
"missing ovftool" when I launch an bento ubuntu on ESXi

### ISSUE THREAD

**Issue by rzhang-nevermore** [josenk/vagrant-vmware-esxi#47]
Hi there, I have an error which says 'missing ovftool' when I use this driver and vagrant to launch a bento ubuntu 16 box on ESXi. How could I resolve this?

**Comment by josenk** [comment]
You resolve this by reading the Requirements section of the README...   :-)   

  You need to install ovftool.
      https://www.vmware.com/support/developer/ovf/

**Comment by rzhang-nevermore** [comment]
where should I install ovftool? on the ESXi server or in my bento box?

**Comment by josenk** [comment]
On your pc/laptop, where you are running vagrant.
