### ISSUE TITLE
can't rerun vagrant up after vagrant destroy

### ISSUE THREAD

**Issue by rzhang-nevermore** [josenk/vagrant-vmware-esxi#48]
I can't run `vagrant up` after I run `vagrant destroy`. I'm getting this error message:

```
Error: Duplicate name 'builder-ubuntu-1604.vagrantup.com' on target. Use --overwrite option to delete it.
STDERR: There was an OVF Tool error.
```

it seems that this driver plugin doesn't clean the VM on the ESXi server when I call `vagrant destroy`.

**Comment by josenk** [comment]
## Known issues with vmware_esxi

    Cleanup doesn't always destroy a VM that has been partially built. To resolve this. Use the local_allow_overwrite = 'True' option if you want to force a rebuild, or you can delete the vm using the VSphere client.


This can happen when you press [CTRL]-C during a vagrant up or vagrant destroy...   As you describe the problem, I have not been able to re-create the problem.   BTW:  You did not provide the vagrantfile you are using and the exact steps to re-create the problem.


If you believe this is a bug.  Turn on debugging, provide the exact steps to re-create the problem, post your vagrantfile, and the debug output.

**Comment by rzhang-nevermore** [comment]
where should I add this option:
`local_allow_overwrite = 'True'`

**Comment by josenk** [comment]
in your vagrantfile

**Comment by rzhang-nevermore** [comment]
hi there, I add that line into my vagrant file, but it didn't work, is there a way that I can explicitly clean up the VMs created on ESXi by this plugin?

**Comment by rzhang-nevermore** [comment]
it seems that OVFtool wants me to add the --overwrite option to it.

**Comment by josenk** [comment]
You still did not provide any debug out or example vagrantfile.   It's not possible to help you very much without providing any details.

BTW:  This pluging will NOT cleanup.   If you [CTRL]-C, you are expected to cleanup your mess using the ESXi console.

Source code is here on Github....
