### ISSUE TITLE
pushing static IP to VM

### ISSUE THREAD

**Issue by sppwf** [josenk/vagrant-vmware-esxi#5]
HI,

Do you think is possible to push static IP to the VM? 
My configs are not taken in consideration :(
	config.vm.network "public_network", auto_config: false 
	config.vm.provision "shell",
	  run: "always",
	  inline: <<-SHELL
		  ifconfig eth0 100.64.4.199 netmask 255.255.255.0 up
		  route add default gw 100.64.4.240
      SHELL

**Comment by clong** [comment]
+1 this request

**Comment by josenk** [comment]
Pushing a static IP is done by the Vagrant application, not by the plugin...    Vagrant keeps track of the IP, so if you manually change it, vagrant will probably get confused...  

https://www.vagrantup.com/docs/networking/private_network.html

**Comment by josenk** [comment]
As per above docs...  Guest operating system support. Private networks generally require configuring the network adapters on the guest machine. This process varies from OS to OS. Vagrant ships with knowledge of how to configure networks on a variety of guest operating systems, but it is possible if you are using a particularly old or new operating system that private networks will not properly configure.


If Vagrant cannot do it, you'll need to get it done as part of the provisioning...   I got a very quick and dirty way to get it working in Centos 7 using nmcli commands...    Give this technique a try.   YMWV

    config.vm.provision "shell",
run: "always",
inline: <<-SHELL
IP="192.168.1.106"
ifconfig|grep -q $IP
if [ $? -ne 0 ];then
  echo "Setting IP to $IP"
  NAME=`nmcli dev|grep connected|head -1|sed 's/^.*connected  //'|sed 's/ *$//'`
  DEV=`nmcli dev|grep connected|head -1|awk '{print $1}'`

  nmcli con mod "$NAME" ipv4.addresses "${IP}/24"
  nmcli con mod "$NAME" ipv4.gateway "192.168.1.1"
  nmcli con mod "$NAME" ipv4.method manual

  nohup sh -c "sleep 5;/usr/sbin/ifdown $DEV ;/usr/sbin/ifup $DEV" &
else
  echo "$IP OK"
fi
exit 0
SHELL

**Comment by josenk** [comment]
I confirmed that Vagrant actually does the IP configuration, however the plugin needs to pass the arguments for that to happen...   I updated my plugin to support your request.  

Vagrant 1.x works very poorly doing this.   I got good results with Vagrant 2.x.

Fixed in vagrant-vmware-esxi V1.4.0...
