### ISSUE TITLE
Feature Request: Specify Diskstore folder

### ISSUE THREAD

**Issue by github-don** [josenk/vagrant-vmware-esxi#55]
Apologies if I've missed this option and it is already an existing feature.

I've identified the `esxi.esxi_disk_store = "store"` command.

However, this places the vagrant-created boxes in the root location. I'd like them all to exist under a `vagrant` folder.

Would it be possible to have an option like:

`esxi.esxi_disk_store_folder = "vagrant"`

Cheers,
Don

**Comment by josenk** [comment]
Sorry, I don't think this is possible... 

Here is the Disk Store options.
>https://github.com/josenk/vagrant-vmware-esxi/wiki/Disk-Storage-options

  This plugin uses ovftool to deploy the boxes to esxi.   There is no option to specify a subdirectory.   The ovftool command line is launched using the (-ds) Disk Store command line arg and the destination is specified by "Inventory Path" (the Resource Pool).  

You can see the command line args used by enabling debug mode.
>https://github.com/josenk/vagrant-vmware-esxi/wiki/Debugging-the-plugin

 I don't even think it's possible to create Guest VMs and place them in subdirectories through the Gui or Web interface when you create new VMs???   This request would break the standards VMware uses to organize their VMs on the hosts.   I don't recommend that you create vms like this on production servers...

If you're looking to deploy infra as code on esxi servers, you may want to use Terraform instead...   My other project.
>https://github.com/josenk/terraform-provider-esxi

**Comment by github-don** [comment]
Thanks for getting back to me.

I don't have the time bandwidth at the moment to go down the rabbit of hole of exploring whether the web interface actually allows this to happen.

Currently I do, however I copy the vmdk/ovf file into a subdirectory and register the VM from there. Then it works no issues.

I'll close the issue.

Cheers,
