### ISSUE TITLE
Cannot communicate with guest machine error

### ISSUE THREAD

**Issue by axelitus** [josenk/vagrant-vmware-esxi#56]
I have set up my guest machine in VMware ESXi perfectly. It's working fine. But every now and then I need to re-provision the machine (when I make a change in the [Homestead](https://laravel.com/docs/5.6/homestead) config).

I randomly get the following error.

```bash
Bringing machine 'homestead-7' up with 'vmware_esxi' provider...
==> homestead-7: Virtual Machine is already built.
==> homestead-7: The VM is already powered_on.
==> homestead-7: --- Configuring     : 192.168.10.10/255.255.255.0 on Homestead Network
==> homestead-7: --- Configuring     : 172.16.1.200/255.255.0.0 on Local Network
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

I immediately re-try and sometimes it works and sometimes I get the same error. But if I keep trying it eventually provisions the machine fine.

My setup can be found in [Getting the ball rolling](https://axel.pardemann.blog/getting-the-ball-rolling/) for reference.

**Comment by josenk** [comment]
Interesting Article with lots of great details.  I'm glad your able to get some good use from the plugin.

   However, there is no code in my plugin that does provisioning...  Provisioning is done by Vagrant.

   Are you re-configuring network in your provisioning?   Vagrant doesn't like it that you modify the primary networking while it's communicating... (actually that would screw up any provisioner like chef, puppet, Ansible, Salt, etc...),

Try disabling the IP Cache (this will force Vagrant to check the Guest IP before every function).
https://github.com/josenk/vagrant-vmware-esxi/wiki/How-to-configure-a-static-IP-on-the-primary-interface

**Comment by axelitus** [comment]
Thanks for your comments!

Actually, I have set up the VM's as you explain in Method 1 of the link you provided. The only thing I'm not doing is setting the `esxi.guest_mac_address` value. I'm relying only on ESXi configuration. I think I have to say that the machine was first created and it has been never destroyed (so it should have the same values).

I'm not trying to change the management IP, I end up having 3 interfaces like:

eth0 -> management interface -> 172.16.1.25
eth1 -> Homestead internal network address -> 192.168.10.10
eth2 -> LAN network address (static) -> 172.16.1.200

Both `eth0` and `eth2` are on the same network. NFS shares are provisioned (the `/etc/exports` file is populated with) through the management network automatically and I have also set configuration entries manually for the IP of `eth2` (so it does not matter what IP is detected for the NFS shares).

I do however think this is a fault in the communication between the host and the guest (Homestead), the strange thing is that in my setup both machines are running on the same ESXi server.

I was uncertain if this was an issue with your plugin, thanks for clarifying it, I'll close this as it is not related to your code and this is an issue with Vagrant itself (and I'm thinking even this is not a problem with Vagrant, but with my network then).

**Comment by josenk** [comment]
Yea, I think its a network issue too...  It's not that you're doing anything really wrong, it's just that the provisioning tool looses contact when the network is configured.    I get the guest ip from vmware tools...   You can turn on ip debuging (and disable ip cache) to see how the detected ip will change as it's being provisioned....
