### ISSUE TITLE
Feature Request - Make it use linked clones rather than creating copies

### ISSUE THREAD

**Issue by chrisurwin** [josenk/vagrant-vmware-esxi#57]
It would be really useful, and significantly faster, if instead of it creating a clone of the disk it created a linked clone so each new machine only created a differencing disk. Most of what I want to do uses the same base image. But thanks for what you've done so far, it's really useful

**Comment by josenk** [comment]
Thanks for the feedback...  I leverage OVFtool to copy the boxes (or clone the sources) and currently OVFtool doesn't support Instant Clones.

"If" OVFtool supports it one day,  I should be able to include this feature in my plugin.   But for now esxi (without vSpere) doesn't have an easy way to support this feature.    This is the second request for this feature, so I know that it would be very useful...

>https://github.com/josenk/vagrant-vmware-esxi/issues/19
