### ISSUE TITLE
How to deal with ova ?

### ISSUE THREAD

**Issue by rgarrigue** [josenk/vagrant-vmware-esxi#59]
Hi

My vmware box is based on an ova instead of ovf + vmx etc. Seems that's a problem for your plugin

```
r.garrigue@AST3169 MINGW64 /d/SOURCES/vagrant/cockpit (master)
$  vagrant up --provider=vmware_esxi

RUBY_PLATFORM: x64-mingw32
Testing esxi connectivity
==> default: --- ESXi version    : VMware ESXi 5.1.0 build-1483097
Bringing machine 'default' up with 'vmware_esxi' provider...
==> default: Box 'company/rhel-6' could not be found. Attempting to find and install...
    default: Box Provider: vmware_esxi, vmware, vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'company/rhel-6' (v0) for provider: vmware_esxi, vmware, vmware_desktop, vmware_fusion, vmware_workstation
    default: Downloading: https://nexus.company.loc/content/sites/packer/rhel-6-x86_64.vmware.box
    default:
==> default: Successfully added box 'company/rhel-6' (v0) for 'vmware_desktop'!
RUBY_PLATFORM: x64-mingw32
Testing esxi connectivity
==> default: Virtual Machine will be built.
VMware ovftool 4.1.0 (build-3634792)
There was an error.
  Unable to open C:/Users/r.garrigue/.vagrant.d/boxes/company-VAGRANTSLASH-rhel-6/0/vmware_desktop/*.vmx

r.garrigue@AST3169 MINGW64 /d/SOURCES/vagrant/cockpit (master)
$ ls C:/Users/r.garrigue/.vagrant.d/boxes/company-VAGRANTSLASH-rhel-6/0/vmware_desktop
metadata.json  rhel-6.9-x86_64.ova  Vagrantfile
```

Is it possible to allow .ova easily in your plugin ?

Best regards,

**Comment by josenk** [comment]
This is not something easily done...   I need the vmx file from the source (either in the box directory, or the clone source on the esxi host) to read information about the source.   An ova file is a single file used to deploy.
Is this box something you packaged?    This doesn't look very typical to me...

As a work-around you could try adding a generic vmx file in your box.   I haven't tried this, but it might work???

**Comment by rgarrigue** [comment]
I've been looking at your code, I understand why you need vmx.

The box is something I packaged using http://packer.io. I wish I could get vmx, but using ova was the only way to get the build working properly, and I've few time left in this job to find a workaround. 

But. I managed to resume work converting ova to vmx with this single command

    ovftool 'C:\Users\r.garrigue\.vagrant.d\boxes\astellia-VAGRANTSLASH-rhel-6\0\vmware_desktop\rhel-6.9-x86_64.ova' 'C:\Users\r.garrigue\.vagrant.d\boxes\astellia-VAGRANTSLASH-rhel-6\0\vmware_desktop\rhel-6.9-x86_64.vmx'

Since it's that easy using ovftool which you're already using, I though you could include this conversion in your code. I'm not a ruby guy, but something like
     
     if not vmx_file.exist?
        other_format_file = Dir.glob(#{thedir}/*.(ova|ovf))
        command ( "ovftool other_format_file vmx_file")

I gave a shot at it but it didn't worked out quickly, maybe because of other issues from my part, but anyway I had to go on with the quick manual workaround.
