### ISSUE TITLE
Passwords that contain symbols generate errors

### ISSUE THREAD

**Issue by clong** [josenk/vagrant-vmware-esxi#6]
It seems that if your password contains symbols, it does not get parsed/escaped correctly at this step:

`Error: Cannot parse locator: vi://root:p@ssw0rd!Containing#Symbols@192.168.x.x`

**Comment by rosenmoore** [comment]
Can confirm.  This is also a problem with ovftool generally and sometimes the error messages are more cryptic.  See [this link](https://communities.vmware.com/thread/429324).  Unfortunately I don't know what that means for this project... maybe we could use 'expect' to prompt the user for a password once at the beginning, validate that, and then automatically fill in the password whenever prompted.  That would also improve user-friendliness for situations where passwordless isn't okay.

**Comment by josenk** [comment]
It would be great if ovftool supported ssh keys.  That would be the best solution.   Need to open Enhancement Requests to VMware.

**Comment by josenk** [comment]
Fixed in V1.2.1

**Comment by mcg** [comment]
I can open a new ticket if needed, but looks like the '$' character wasn't included in the special character escaping. Can this been included?

**Comment by josenk** [comment]
Fixed in V1.5.0.   Added $ symbol.

**Comment by int0x80** [comment]
Dies on a password with spaces. Sorry to re-open.

**Comment by josenk** [comment]
Sure, NP!   Completely resolving these issues just makes the software better...   It should be fixed in the next release...

**Comment by josenk** [comment]
Fixed in V2.0.2

**Comment by lenogwan** [comment]
Dies on password with / symbol running.  Can this been included?

**Comment by josenk** [comment]
Sure, It should be fixed in the next release...

**Comment by Thomas8996** [comment]
Look like ' ; ' character wasn't included in the special character escaping,  Can this been included?

**Comment by josenk** [comment]
Fixed in 2.2.0.  I added a bunch of other special characters too!
