### ISSUE TITLE
Dependency i18n v0.6 should be update to 1.1.1

### ISSUE THREAD

**Issue by lapawa** [josenk/vagrant-vmware-esxi#62]
I'm using vagrant 2.2.1 from https://www.vagrantup.com which ships with his own ruby gem i18n in version 1.1.1.
This blocks the installation of vagrant-vmware-esxi.
Can you please update the dependencies from ~>0.6 to 1.1.1?
Thanks

**Comment by haiderim** [comment]
I have the same issue but I guess you can just edit the vagrant-vmware-esxi.gemspec. I'll try following https://3ofcoins.net/2013/06/10/installing-vagrant-plugins-from-local-file/ and see if it helps

**Comment by josenk** [comment]
Installing from local will give the same problem....  It's just a matter of updating the dependencies.

 Now fixed in 2.4.2.  You should be able to install now.

**Comment by haiderim** [comment]
Works now, thanks for the quick fix.
