### ISSUE TITLE
Verify password in Vagrantfile is correct

### ISSUE THREAD

**Issue by sinasalek** [josenk/vagrant-vmware-esxi#63]
The server access info including the password is correct, i checked it by connecting remotely. However i keep seeing the error. Is this a bug? note that i tried it with vmware workstation (15) and esxi (6.7) with same result
```
==> default: --- ESXi host access : Verify password in Vagrantfile is correct.
There was an error talking to ESXi.
  Unable to connect to ESXi host!
```

**Comment by josenk** [comment]
Are you using any special characters?   There has been problems with that in the past...
>https://github.com/josenk/vagrant-vmware-esxi/issues/6

   Have you enabled ssh access to the esxi host? 

Btw, this plugin only works fpr esxi.   It will not work for workstation.

**Comment by josenk** [comment]
The above error message is same.   It's unable to connect to your esxi host.  There is just additional text from Vagrant itself.

1) Verify you have the correct hostname/IP in your Vagrantfile.
2) Verify you can login on your esxi host as root using the password specified in the Vagrantfile.
3) Please run "vmware --version" on your esxi host and post here the results.
4) While trying Vagrant, do a "tail -f /var/log/auth.log" on your esxi host.   There could be messages there that could indicate your problem.
