### ISSUE TITLE
I am not sure how this plugin works: Provider expected: vmware Provider of box: vmware_desktop

### ISSUE THREAD

**Issue by MiniMe4GH** [josenk/vagrant-vmware-esxi#65]
O don't get it, it says could not be found 
then is says
default: Box Provider: vmware_esxi, vmware, vmware_desktop, vmware_fusion, vmware_workstation
and it downloads the workstation version?!
What really happened here?

vagrant up --provider=vmware_esxi

root@10.16.31.235 password:
Bringing machine 'default' up with 'vmware_esxi' provider...
==> default: Box 'generic/ubuntu1710' could not be found. Attempting to find and install...
    default: Box Provider: vmware_esxi, vmware, vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Loading metadata for box 'generic/ubuntu1710'
    default: URL: https://vagrantcloud.com/generic/ubuntu1710
==> default: Adding box 'generic/ubuntu1710' (v1.8.50) for provider: vmware
    default: Downloading: https://vagrantcloud.com/generic/boxes/ubuntu1710/versions/1.8.50/providers/vmware.box
    default: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    default: Progress: 100% (Rate: 3286k/s, Estimated time remaining: --:--:--)
The box you attempted to add doesn't match the provider you specified.

Provider expected: vmware
Provider of box: vmware_desktop

**Comment by josenk** [comment]
Did you read the Features???  This plugin is compatible with many Box formats.   You should be able to choose any of the compatible formats.  The "native" format is "vmware", however it will download and use any of the compatible formats.

Any of the vmware Box formats should be compatible.
    vmware_desktop, vmware_fusion, vmware_workstation...

 This tool uses ovftool to copy the Boxes to esxi.  I highly recommend reading the documentation.
