### ISSUE TITLE
DS can't be found with ESXi 6.7

### ISSUE THREAD

**Issue by scaleoutsean** [josenk/vagrant-vmware-esxi#67]
Had the same problem as https://github.com/josenk/vagrant-vmware-esxi/issues/41#issuecomment-390481282, but it wasn't the password (even leaving the DS empty wouldn't work, rescan didn't help (wasn't required) either).

Based on the comment linked above, I changed that line to:
`r = ssh.exec!('esxcli storage filesystem list | grep "/vmfs/volumes/.*[VMFS|NFS]" | awk \'{ print $2}\'')`

That fixed it for me.

* vagrant-vmware-esxi (2.4.1, global)
* vagrant: 2.2.0
* ESXi: 6.7

**Comment by scaleoutsean** [comment]
It was like in the linked issue - the plugin gets to ESXi but doesn't get any eligible DS's back (even if I paste the line in an SSH session within ESXi 6.7). From the client I get no DS available. But with that hack the plugin works for me. 

> If I implemented it

Please don't get me wrong, it wasn't a PR - it's just community sharing for those who have the same problem. 

If you'd like a detailed bug report, please let me know what info you need and I'll start from the beginning (with the unpatched plugin).

**Comment by josenk** [comment]
As you can see, sed/awk is a bit buggy and doesn't have all the functionality of a full blown Linux system.  

The double space field separator was required to support Disk Stores with a space. (if you have a double space in your disk store name, then it wouldn't work).  You need to have the sort in there to use the correct disk store when it's not specified or using "Least used".

I still don't fully understand why this is not working for you???  MANY people are using this plugin and do not have this problem.  Let me break down the commands to help figure this out.  Maybe you can find where it's breaking...

```
esxcli storage filesystem list |     // The command to print all the filesystems and size, usage.
grep "/vmfs/volumes/.*[VMFS|NFS]" |  // Filter to show only filesystems that are VMFS or NFS 
awk -F'  ' '{print $NF\",\"$2}' |    //  Doublespace separator, print the last field, comma & field2
sort -n |                            // Sort numerically on field 1. Largest will be last
awk -F',' '{print $2}'               // Print the disk store names using comma delimiter 
```

I've figured out another way without using double space field separators...   Please test this command and let me know if it works correctly.   It should print the free space, a comma, then the disk store name.  Also, I would really appreciate it if you could rename your disk stores with spaces temporarily to see if this command still outputs the complete disk store name in the correct sorted order.

```
esxcli storage filesystem list|grep '^/vmfs/.*[VMFS|NFS]'|awk '{printf $NF"," ; for(i=2;i<=NF-5;++i)printf $i""FS ; print ""}'|sort -n
```

**Comment by josenk** [comment]
2.4.3 released with fix.
>https://github.com/josenk/vagrant-vmware-esxi/releases/tag/2.4.3
