### ISSUE TITLE
Unable to read /vmfs/volumes/datastore1\ (2)/V-pu-santi-swarm/V-pu-santi-swarm.vmx

### ISSUE THREAD

**Issue by puzhengwu** [josenk/vagrant-vmware-esxi#68]
==> default: --- VMID            : 8
There was an error talking to ESXi.
  Unable to read /vmfs/volumes/datastore1\ (2)/V-pu-santi-swarm/V-pu-santi-swarm.vmx

**Comment by josenk** [comment]
Is that the name of your disk store???   You'll need to provide more details than this if you would like help...

**Comment by josenk** [comment]
2.4.3 released with fix.
>https://github.com/josenk/vagrant-vmware-esxi/releases/tag/2.4.3
