### ISSUE TITLE
Feature Request: Support overrides

### ISSUE THREAD

**Issue by clong** [josenk/vagrant-vmware-esxi#7]
Supporting overrides allows people to include multiple different providers in their Vagrantfile. Current output while trying to use this is:

```
$ vagrant up myhost --provider=vmware_esxi
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: <provider config: vmware_esxi>
Line number: 89
Message: NameError: undefined local variable or method `override' for main:Object
```

More info here: https://www.vagrantup.com/docs/providers/configuration.html#overriding-configuration

**Comment by josenk** [comment]
Verify your Vagrantfile...   I was able to make it work.   Make sure you add the "override" on the config.vm.provider line.

config.vm.provider :vmware_esxi do |esxi, override|

https://www.lightnetics.com/topic/2826/message-nameerror-undefined-local-variable-or-method-override-for-main-object

If you cannot get it working, please paste your Vagrantfile here.  (be sure to remove any private information!)

**Comment by clong** [comment]
Hey @josenk,

I'm sorry for the delayed response here - I'm currently on vacation and don't have the ability to test against my ESXI server. However, I'm pretty sure I forgot the `override` in `do |esxi, override|`, so if you were able to test successfully, feel free to close this one out. Thanks so much for addressing issues so quickly - this project is awesome!

**Comment by josenk** [comment]
No problem.  No rush.   I'm glad you like my project and thank you for all the feedback!

**Comment by josenk** [comment]
No problem.  No rush.   I'm glad you like my project and thank you for all the feedback!
