### ISSUE TITLE
ssh and network fail

### ISSUE THREAD

**Issue by Zun1k** [josenk/vagrant-vmware-esxi#72]
Hi all

I got a problem with starting VM on vmware. I had tried many boxes of Cento5,6 and 7 (for vmware with tools), many configurations, but nothing works. I read all your closed tickets a tried all what I can.

We wanna start some Centos 6, Centos 7 and Win2012r2 VM automatically from vagrant without any manual work. 

- What I have
  - `vagrant up` created a VM on vmware host with cpu, ram, network cards and etc... but ssh not working, network is not set and vagrant ends on timeout.... After manual reconfiguration of ssh and network, vagrant can finish and `vagrant ssh` works

After reconfiguration for virtualbox it works very well, but vmware esxi nope :( only way is : 
1. run vagrant up
2. during failed ssh connecting, configure network manually togather with sshd_config for allow ssh connection with password.
3. if you quickly configure it all, vagrant is able to set hostname and successfully end

- What I tried
  - start vm without network settings
  - exclude hostname
  - tried many boxes include ubuntu and other from your examples
  - tried your examples for static ip, single vm, multiple vm
  - clean network settings in VM but it doesn't work because `vagrant reload` is not working I think due to ssh problem (so repackage is needed)
  - tried create updated box via [tutorial](https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one) but ends on `There was an OVF Tool error`

- VMware  settings:
  -  one "VM Network" with 192.168.35.0/24. Vagrant is called from one of the VM on this vmware host.
- here is my [Vagrantfile.txt](https://github.com/josenk/vagrant-vmware-esxi/files/2751106/Vagrantfile.txt)
- here is my [DebugLog.txt](https://github.com/josenk/vagrant-vmware-esxi/files/2751184/DebugLog.txt)

- versions:
  - Vagrant host - Centos 7 
  - Vagrant version: 2.2.3
  - vagrant-vmware-esxi (2.4.3, global)
  - vmware esxi 6.0.

We wanna start a lot of virtual machines and do it manually is pain. 
I hope it's not a duplicate , as far I know it's not problem of your plugin but can you help me somehow?
Also pls apologize my english :)

Thx a lot for any help

**Comment by Zun1k** [comment]
Hi josenk , wow thank you for so quick answer, 

We wanna automatize manual process, now we are using two interfaces for each VM (one for VM network, other for internet). I assume we need three interfaces for vagrant (eth0/dhcp for management network, eth1/static 192.168.35.71/24, eth2 192.168.135.71/24) eth1 and eth2 dont have same subnet, what about dhcp?Why same subnets doesnt work? :( Should I reconfigure eth0 for static as you described [here](https://github.com/josenk/vagrant-vmware-esxi/wiki/How-to-configure-a-static-IP-on-the-primary-interface) 

Nevermind, lets analyze vagrant without network first...
**It doesnt work :(** , here is debug log [DebugLog2.txt](https://github.com/josenk/vagrant-vmware-esxi/files/2751848/DebugLog2.txt)

Here is vmware screen: ![screen](https://user-images.githubusercontent.com/44600133/51071458-68ec7600-1651-11e9-9bd6-436848c6ed73.png)

Here are logs from host (/var/log/messages) ![messages](https://user-images.githubusercontent.com/44600133/51071519-71917c00-1652-11e9-9a92-e35a83a29bac.png)

Here interface information ![eth0](https://user-images.githubusercontent.com/44600133/51071529-9685ef00-1652-11e9-9bb2-3a8b9c403d04.png)


Thx

**Comment by josenk** [comment]
You must have a dhcp server on that first interface.

**Comment by Zun1k** [comment]
Hi, 
Thanks a lot for support 

Please update your documentation, some 'vmware prerequisites' (there should be dhcp server running on ESXI hypervisor)
[guide](https://www.tecmint.com/install-dhcp-server-in-centos-rhel-fedora/) for centos7 works well 

amazing plugin :)
