### ISSUE TITLE
Question: clone_from_vm with folder/resource_pool on ESXi free?

### ISSUE THREAD

**Issue by rgl** [josenk/vagrant-vmware-esxi#74]
The [How to clone_from_vm](https://github.com/josenk/vagrant-vmware-esxi/wiki/How-to-clone_from_vm) recommends putting the template vms inside a folder or resource_pool, but how do you create those on ESXi free?

**Comment by josenk** [comment]
Pre esxi 6.7 supports the thick client (RIP) . It was easy to do it there...  I could be wrong, but I don't think the new esxi web ui supports managing resource pools at all. 

My recommendation is to use Terraform (I created a plugin for terraform also).  There's examples in the readme. 

   If you're handy with the command line and don't want to use terraform , Google shows you how.

**Comment by rgl** [comment]
Oh interesting... I didn't known there were features in ESXi free that were not exposed by their UI. Do the resource pools actually work (like, in restricting the CPU, etc)?

Even thou you cannot create the resource pool from the UI, will the UI show them?

I will try the terraform provider too!

**Comment by josenk** [comment]
abandoned
