### ISSUE TITLE
vmdk file is not being transferred to esxi

### ISSUE THREAD

**Issue by maxsatula** [josenk/vagrant-vmware-esxi#75]
Vagrant Version: 2.2.3
vagrant-vmware-esxi (2.4.3, global)
VMware ovftool 4.3.0 (build-7948156)

I made a `.box` file with `packer`  with `"type": "vmware-iso"`

First issue is that once vagrant extracts `.box` into `.vagrant.d` directory, there is no `.vmx` file but `.ovf` instead. Ok, I extracted a missing `.vmx` from `.ovf` manually by `ovftool` and put it in the same directory to workaround that.

However, when I run `vagrant up`, it uploads `.vmx` file to ESXi, but **does not upload the disk image `.vmdk`** from my system where I run vagrant.

Here are relevant lines in the VMX file:
```
scsi0:0.present = "TRUE"
scsi0:0.deviceType = "disk"
scsi0:0.fileName = "packer-oel7-base-disk1.vmdk"
scsi0:0.allowguestconnectioncontrol = "false"
scsi0:0.writeThrough = "false"
scsi0:0.mode = "persistent"
```
the `packer-oel7-base-disk1.vmdk` file exists in the same directory as VMX file, `.vagrant.d/boxes/<myvmname>/0/vmware_desktop/`

Your help is much appreciated

**Comment by josenk** [comment]
I'm not sure how packer works...  I have never used it and I don't support it.  But it sounds like you may be missing something to produce the correct box contents.

**Comment by maxsatula** [comment]
@josenk, I guess that would be nice to have Packer supported, since it belongs to the same HashiCorp Suite family as Vagrant does. And I do not know of a better way to build a custom box provided that having a custom box is necessary.
I do not want to pollute this conversation by spitting out complete VMX content. Could you please give a basic hint where I want to look at? Honestly, I could not even find a piece of source code where you upload `*.vmdk` to ESXi. So the primary question is, does it make sense to dig further, was it your intention to upload a disk image to ESXi at first place?
Thank you

**Comment by maxsatula** [comment]
Seems to be an `ovftool` issue

https://github.com/josenk/vagrant-vmware-esxi/blob/a999bf6ae2aef3ec74491bd8eee53d1a090841f8/lib/vagrant-vmware-esxi/action/package.rb#L95

**Comment by josenk** [comment]
Sorry, I don't support packer or ovftool for that matter...   It's probably because you chose type vmware-iso.  You should try other types.
 
 My suggestion is to start with the basics and work your way up to packer when you fully understand how things works.

When you post a problem, you need to post your vagrant file and the debug output.

**Comment by maxsatula** [comment]
Hi @josenk,
Yes you are right, I chose type **vmware-iso**, because that is a business need to run a custom Linux installation. Could you please do me a favor and point out what exactly is wrong with **vmware-iso** type? Obviously you know something about it.

**Comment by josenk** [comment]
What is iso image format...
 https://en.m.wikipedia.org/wiki/ISO_image

Link with some info about formats. 
  https://spin.atomicobject.com/2013/06/03/ovf-virtual-machine/

You may want to read the ovftool manual for more information.

**Comment by maxsatula** [comment]
@josenk, thanks but I know what ISO format is.
*vmware-iso* type takes an ISO image for initial OS installation only. However, once a box finishes building with this type (please do not get confused by having "iso" as a part of its name), it contains a full fledged VM image with a `*.vmdk` real disk file attached to a SCSI bus as a hard drive, not ISO, not CD. Here is why I opened an issue at first place.
"ISO" in *vmware-iso" stands for the way how you build your VM, from which source, *not* about what you have as a result. Once again, it results with a complete VM image which has a hard drive image.
