### ISSUE TITLE
Feature Request: Autostart (+Parameters)

### ISSUE THREAD

**Issue by egandro** [josenk/vagrant-vmware-esxi#79]
It would be super cool to have autostart as parameter.

I a figuring out the CLI options and post them here.

**Comment by josenk** [comment]
Yes, I think that's a good idea.

**Comment by egandro** [comment]
# website: http://sakananote2english.blogspot.com/2012/04/power-on-vm-with-command-line-at-vmware.html


# enable the autostart manager (if this is not enabled, no autostart will happen)

```
$ vim-cmd hostsvc/autostartmanager/enable_autostart 1
```

# suggested vmware_esxi mapping
```
    #  ESXi enable autostart manager if not running
    #esxi.autostartmanager_enable_autostart = true
```

# get defaults for the autostart manager (just for info)

```
$ vim-cmd vim.host.AutoStartManager.SystemDefaults
```

# get the VM ID of a given guest (we migth not need this, we have the pid - just for info)

```
$ export $VmID=$(vim-cmd vmsvc/getallvms | grep ${esxi_guest_name} | cut -b 1-5)
```

# make the given vm start at first order (example)

```
$ vim-cmd hostsvc/autostartmanager/update_autostartentry $VmID 'PowerOn' 'systemDefault' '1' 'systemDefault' 'systemDefault' 'systemDefault'
```

```
# [root@esxi:~] vim-cmd hostsvc/autostartmanager/update_autostartentry
# Usage: update_autostartentry VMId StartAction StartDelay StartOrder StopAction StopDelay WaitForHeartbeat

Parameters:

- VmID
- startAction = "none", "powerOn"
- startDelay = Number or 'systemDefault'
- startOrder = Number
- stopAction = "powerOff" or "suspend" or "guestShutdown" or "systemDefault"
- stopDelay = Number or "systemDefault"
- waitForHeartbeat = "yes" / "no" / "systemDefault"
```


# suggested vmware_esxi mapping (in order of parameters)

```
    #  ESXi autostart startAction - set to true for enabling
    #esxi.autostart = false

    #  ESXi autostart startDelay - if not set system default will be used
    #esxi.startDelay = 120

    #  ESXi autostart startOrder - if not set 1 will be the default
    #esxi.startOrder = 1

    #  ESXi autostart stopAction - if not set system default will be used
    #esxi.stopAction = "powerOff" or "suspend" or "guestShutdown"

    #  ESXi autostart stopDelay - if not set system default will be used
    #esxi.stopDelay = 120

    #  ESXi autostart waitForHeartbeat (boolean) - if not set system default will be used
    #esxi.waitForHeartbeat = false
```


# show autostart entries (just for info)

```
$ vim-cmd hostsvc/autostartmanager/get_autostartseq
```

**Comment by egandro** [comment]
I'd like to work on this.

@josenk  can you please point me to a way how to code on a git version of the plugin?

I am only familiar with "vigrant plugin install" - which of course installs this via a vagrant repo.

**Comment by josenk** [comment]
I used other provider examples to configure the build environment...   Check out some examples and you should be able to figure it out.
>https://github.com/vagrant-libvirt/vagrant-libvirt#development

**Comment by josenk** [comment]
https://github.com/josenk/vagrant-vmware-esxi/releases/tag/v2.5.0
