### ISSUE TITLE
enhance "Unable to connect to ESXi host!"

### ISSUE THREAD

**Issue by egandro** [josenk/vagrant-vmware-esxi#80]
I reinstalled the server.

vagrant-vmware-esxi saves the ssh keys in $HOME/.ssh/known_hosts

so with this default error "Unable to connect to ESXi host!"

I couldn't see what was causing the issue. This might be enhanced / put the ssh error to console

**Comment by egandro** [comment]
I have a semifix for this.

Since I install my ESXi via qemu/rescue system I always have a ssh keychange.

So I do this before any vigrant commands

```ssh-keygen -R $MACHINE_IP```

**Comment by josenk** [comment]
Should be fixed:
> https://github.com/josenk/vagrant-vmware-esxi/releases/tag/2.4.4
