### ISSUE TITLE
plugin does not see ovftool in OSX 10.14.3

### ISSUE THREAD

**Issue by fsvdonets** [josenk/vagrant-vmware-esxi#81]
macOS Mojave 10.14.3
Vagrant 2.2.3
vagrant-vmware-esxi (2.4.3, global)
VMware ovftool 4.3.0 (build-7948156)

when I run "vagrant up" I am getting this error:

`Bringing machine 'default' up with 'vmware_esxi' provider...
==> default: Virtual Machine will be built.
Error: Locale initialization failed.
Completed with errors
There was an OVF Tool error.
  ovftool not found or not in your path.  Please download and   install from http://www.vmware.com.`

my path '$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware OVF Tool/'

I can run 'ovftool --version' just fine.

**Comment by josenk** [comment]
The actual error is:
   Locale initialization failed. 

You can enable debugging to see the command line used.  Try running it manually.   In your Vagrantfile, debug = "true ovftool"

Unfortunately I do not have a Mac to try recreating this issue...

**Comment by josenk** [comment]
abandoned

**Comment by DijixH** [comment]
I reply maybe too late, but for other user of MacOS I think I have a solution. 

In the terminal where you want to execute you're ``vagrant up`` command you can make ``export PATH=/Applications/VMware\ OVF\ Tool/:$PATH`` (this is the path of my OVF tool it doesn't include in VMWare Fusion Tech Preview packages). This command work only on the terminal window you have opened.

If you want to make the ovftool command permanently you can add OVF tool directory in ``/etc/paths``, I didn't try this second method. 

Hope I help you !

**Comment by jiubujian** [comment]
> 

thank you, it's useful.
I use vmware fusion 12 and OVF tool is already installed. I add `export PATH="/Applications/VMware Fusion.app/Contents/Library/VMware OVF Tool:$PATH"` to ~/.zshrc and it works.
