### ISSUE TITLE
extra network connect

### ISSUE THREAD

**Issue by redwiz666** [josenk/vagrant-vmware-esxi#82]
When building a VM there is always at least 2 connections. I have checked my vagrant file and only one is listed? How can i have only use that 1 connection and not build an additional one unless needed?

**Comment by redwiz666** [comment]
I found the issue and fixed it. I created a pull request with the fix.

**Comment by josenk** [comment]
You need to provide more details.   Update this thread with the Vagrantfile and which Vagrant box you are using.   If it's a home-grown Vagrant Box, please upload it's vmx file.

**Comment by josenk** [comment]
Abandoned
