### ISSUE TITLE
Scheduled next release?

### ISSUE THREAD

**Issue by egandro** [josenk/vagrant-vmware-esxi#87]
Hello Josnk,

any plans when you will create the next release?

You added my patch request for "darwin18-64" and "darwin19-64" but they are still not in the official vagrant version.

**Comment by josenk** [comment]
What do you mean "They are not in the official vagrant version"???   I do the plugin here...   This is not the official vagrant git repo.

But, I did add the latest Darwins...   Please try "vagrant plugin update".
> https://github.com/josenk/vagrant-vmware-esxi/releases/tag/2.4.4

**Comment by egandro** [comment]
https://github.com/josenk/vagrant-vmware-esxi/blob/master/lib/vagrant-vmware-esxi/config.rb

You merged here the "'darwin18-64', 'darwin19-64'.

In my versions there are none of there entries.

-> I will try the update! Thx.

**Comment by egandro** [comment]
Thanks a lot. I found the problem.

I am here on Windows - using WSL. I enabled this:

```
export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS='1'
```

so vagrant uses the Windows version not the Linux version :) 

Sorry for that!
