### ISSUE TITLE
Feature Request: Set MAC address

### ISSUE THREAD

**Issue by lkys37en** [josenk/vagrant-vmware-esxi#9]
I would like to see the ability to set a manual mac address.

**Comment by josenk** [comment]
I updated the plugin to support this request.  However!!!   If you enter a VMware reserved IP address or anything that ESXi considers invalid, your guest will not power up...  

Look at README.md for instructions how to set the mac_address.

Fixed in vagrant-vmware-esxi V1.4.0...
