### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

### ISSUE THREAD

**Issue by caesarleong** [josenk/vagrant-vmware-esxi#93]
the error easy to show up when multiple machine setup

this is the log

=========================================================================
vagrant up

Bringing machine 'db_primary' up with 'vmware_esxi' provider...
Bringing machine 'db_replication' up with 'vmware_esxi' provider...
Bringing machine 'king' up with 'vmware_esxi' provider...
Bringing machine 'lady' up with 'vmware_esxi' provider...
Bringing machine 'partner' up with 'vmware_esxi' provider...
==> partner: Virtual Machine will be built.
==> db_replication: Virtual Machine will be built.
==> lady: Virtual Machine will be built.
VMware ovftool 4.3.0 (build-13981069)
==> king: Virtual Machine will be built.
==> db_primary: Virtual Machine will be built.
VMware ovftool 4.3.0 (build-13981069)
VMware ovftool 4.3.0 (build-13981069)
VMware ovftool 4.3.0 (build-13981069)
VMware ovftool 4.3.0 (build-13981069)
==> db_replication: --- WARNING         : esxi_disk_store not set, using "--- Least Used ---"
==> king: --- WARNING         : esxi_disk_store not set, using "--- Least Used ---"
==> partner: --- WARNING         : esxi_disk_store not set, using "--- Least Used ---"
==> db_primary: --- WARNING         : esxi_disk_store not set, using "--- Least Used ---"
==> lady: --- WARNING         : esxi_disk_store not set, using "--- Least Used ---"
==> partner: ---   --- ESXi Summary ---
==> partner: --- ESXi host       : 10.0.1.22
==> partner: --- Virtual Network : ["Dev Cat Network", "Dev Cat Network", "Dev Cat Network"]
==> partner: --- Disk Store      : datastore1
==> partner: --- Resource Pool   : /
==> partner: ---  --- Guest Summary ---
==> partner: --- VM Name         : dev-cat-partner
==> partner: --- Box             : centos/7
==> partner: --- Box Ver         : 1905.1
==> partner: --- Memsize (MB)    : 512
==> partner: --- CPUS            : 1
==> partner: --- Boot Disk Size  : [10]GB
==> partner: --- Guest OS type   : centos7-64
==> partner: ---   --- Guest Build ---
==> lady: ---   --- ESXi Summary ---
==> lady: --- ESXi host       : 10.0.1.22
==> lady: --- Virtual Network : ["Dev Cat Network", "Dev Cat Network", "Dev Cat Network"]
==> lady: --- Disk Store      : datastore1
==> lady: --- Resource Pool   : /
==> lady: ---  --- Guest Summary ---
==> lady: --- VM Name         : dev-cat-lady
==> king: ---   --- ESXi Summary ---
==> lady: --- Box             : centos/7
==> king: --- ESXi host       : 10.0.1.22
==> lady: --- Box Ver         : 1905.1
==> king: --- Virtual Network : ["Dev Cat Network", "Dev Cat Network", "Dev Cat Network"]
==> lady: --- Memsize (MB)    : 512
==> king: --- Disk Store      : datastore1
==> lady: --- CPUS            : 1
==> lady: --- Boot Disk Size  : [10]GB
==> lady: --- Guest OS type   : centos7-64
==> king: --- Resource Pool   : /
==> db_primary: ---   --- ESXi Summary ---
==> lady: ---   --- Guest Build ---
==> db_primary: --- ESXi host       : 10.0.1.22
==> db_replication: ---   --- ESXi Summary ---
==> king: ---  --- Guest Summary ---
==> db_primary: --- Virtual Network : ["Dev Cat Network", "Dev Cat Network", "Dev Cat Network"]
==> db_replication: --- ESXi host       : 10.0.1.22
==> king: --- VM Name         : dev-cat-king
==> db_primary: --- Disk Store      : datastore1
==> db_replication: --- Virtual Network : ["Dev Cat Network", "Dev Cat Network", "Dev Cat Network"]
==> king: --- Box             : centos/7
==> db_primary: --- Resource Pool   : /
==> king: --- Box Ver         : 1905.1
==> db_replication: --- Disk Store      : datastore1
==> db_primary: ---  --- Guest Summary ---
==> king: --- Memsize (MB)    : 512
==> db_replication: --- Resource Pool   : /
==> db_primary: --- VM Name         : dev-cat-db-primary
==> db_replication: ---  --- Guest Summary ---
==> db_primary: --- Box             : centos/7
==> db_replication: --- VM Name         : dev-cat-db-replication
==> db_primary: --- Box Ver         : 1905.1
==> db_replication: --- Box             : centos/7
==> db_primary: --- Memsize (MB)    : 512
==> db_replication: --- Box Ver         : 1905.1
==> db_primary: --- CPUS            : 1
==> db_replication: --- Memsize (MB)    : 512
==> db_replication: --- CPUS            : 1
==> db_primary: --- Boot Disk Size  : [10]GB
==> db_replication: --- Boot Disk Size  : [10]GB
==> db_primary: --- Guest OS type   : centos7-64
==> db_primary: ---   --- Guest Build ---
==> db_replication: --- Guest OS type   : centos7-64
==> king: --- CPUS            : 1
==> db_replication: ---   --- Guest Build ---
==> king: --- Boot Disk Size  : [10]GB
==> king: --- Guest OS type   : centos7-64
==> king: ---   --- Guest Build ---
Opening VMX source: /home/caesar/.vagrant.d/boxes/centos-VAGRANTSLASH-7/1905.1/vmware_desktop/ZZZZ_dev-cat-partner.vmx
Opening VI target: vi://vagrant@10.0.1.22:443/
Opening VMX source: /home/caesar/.vagrant.d/boxes/centos-VAGRANTSLASH-7/1905.1/vmware_desktop/ZZZZ_dev-cat-lady.vmx
Opening VMX source: /home/caesar/.vagrant.d/boxes/centos-VAGRANTSLASH-7/1905.1/vmware_desktop/ZZZZ_dev-cat-king.vmx
Opening VMX source: /home/caesar/.vagrant.d/boxes/centos-VAGRANTSLASH-7/1905.1/vmware_desktop/ZZZZ_dev-cat-db-replication.vmx
Opening VMX source: /home/caesar/.vagrant.d/boxes/centos-VAGRANTSLASH-7/1905.1/vmware_desktop/ZZZZ_dev-cat-db-primary.vmx
Opening VI target: vi://vagrant@10.0.1.22:443/
Opening VI target: vi://vagrant@10.0.1.22:443/
Opening Opening VIVI target:  target: vi://vagrant@10.0.1.22:443/vi://vagrant@10.0.1.22:443/

Deploying to VI: vi://vagrant@10.0.1.22:443/
Deploying to VI: vi://vagrant@10.0.1.22:443/
Deploying to VI: vi://vagrant@10.0.1.22:443/
Deploying to VI: vi://vagrant@10.0.1.22:443/
Deploying to VI: vi://vagrant@10.0.1.22:443/
Transfer Completed                    
Transfer Completed                    
Disk progress: 90%Completed successfully
Transfer Completed                    
Disk progress: 93%==> lady: --- VMID            : 155
Disk progress: 92%Completed successfully
Disk progress: 99%==> db_replication: --- VMID            : 158
Transfer Completed                    
Disk progress: 97%Completed successfully
Transfer Completed                    
==> king: --- VMID            : 156
Completed successfully
==> lady: --- VM has been Powered On...
==> db_primary: --- VMID            : 157
Completed successfully
==> db_replication: --- VM has been Powered On...
==> partner: --- VMID            : 154
==> lady: --- Waiting for state "running"
==> king: --- VM has been Powered On...
==> db_replication: --- Waiting for state "running"
==> king: --- Waiting for state "running"
==> db_primary: --- VM has been Powered On...
==> db_primary: --- Waiting for state "running"
==> partner: --- VM has been Powered On...
==> partner: --- Waiting for state "running"
==> lady: --- Success, state is now "running"
==> lady: --- Configuring     : 10.0.3.120/255.0.0.0 on Dev Cat Network
==> lady: --- Configuring     : 192.168.10.120/255.255.255.0 on Dev Cat Network
    lady: 
    lady: Vagrant insecure key detected. Vagrant will automatically replace
    lady: this with a newly generated keypair for better security.
    lady: 
    lady: Inserting generated public key within guest...
    lady: Removing insecure key from the guest if it's present...
    lady: Key inserted! Disconnecting and reconnecting using new SSH key...
==> db_replication: --- Success, state is now "running"
==> db_replication: --- Configuring     : 10.0.3.101/255.0.0.0 on Dev Cat Network
==> db_replication: --- Configuring     : 192.168.10.101/255.255.255.0 on Dev Cat Network
    lady: SSH address: 10.0.1.139:22
    lady: SSH username: vagrant
    lady: SSH auth method: private key
==> lady: Setting hostname...
==> king: --- Success, state is now "running"
==> king: --- Configuring     : 10.0.3.110/255.0.0.0 on Dev Cat Network
==> king: --- Configuring     : 192.168.10.110/255.255.255.0 on Dev Cat Network
==> lady: Rsyncing folder: /home/caesar/Work/cat/dev_cat/cat_ansible/ => /vagrant
==> db_primary: --- Success, state is now "running"
==> db_primary: --- Configuring     : 10.0.3.100/255.0.0.0 on Dev Cat Network
==> db_primary: --- Configuring     : 192.168.10.100/255.255.255.0 on Dev Cat Network
    king: 
    king: Vagrant insecure key detected. Vagrant will automatically replace
    king: this with a newly generated keypair for better security.
==> partner: --- Success, state is now "running"
==> partner: --- Configuring     : 10.0.3.130/255.0.0.0 on Dev Cat Network
==> partner: --- Configuring     : 192.168.10.130/255.255.255.0 on Dev Cat Network
    king: 
    king: Inserting generated public key within guest...
    king: Removing insecure key from the guest if it's present...
    king: Key inserted! Disconnecting and reconnecting using new SSH key...
    king: SSH address: 10.0.1.141:22
    king: SSH username: vagrant
    king: SSH auth method: private key
==> db_replication: An error occurred. The error will be shown after all tasks complete.
==> king: Setting hostname...
==> king: Rsyncing folder: /home/caesar/Work/cat/dev_cat/cat_ansible/ => /vagrant
==> db_primary: An error occurred. The error will be shown after all tasks complete.
==> partner: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'db_primary'
machine. Please handle this error then try again:

Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

An error occurred while executing the action on the 'db_replication'
machine. Please handle this error then try again:

Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

An error occurred while executing the action on the 'partner'
machine. Please handle this error then try again:

Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

=========================================================================

this is the Vagrantfile

=========================================================================

# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { define: 'db_primary', hostname: 'cat-db-primary', public_ip: '10.0.3.100', private_ip: '192.168.10.100', 
    cpus: '1', mem: '512', storage: [10], synced_folder: 'vagrant_shared/db_primary'},
  { define: 'db_replication', hostname: 'cat-db-replication', public_ip: '10.0.3.101', private_ip: '192.168.10.101', 
    cpus: '1', mem: '512', storage: [10], synced_folder: 'vagrant_shared/db_replication'},
  { define: 'king', hostname: 'cat-king', public_ip: '10.0.3.110', private_ip: '192.168.10.110', 
    cpus: '1', mem: '512', storage: [10], synced_folder: 'vagrant_shared/king'},
  { define: 'lady', hostname: 'cat-lady', public_ip: '10.0.3.120', private_ip: '192.168.10.120', 
    cpus: '1', mem: '512', storage: [10], synced_folder: 'vagrant_shared/lady'},
  { define: 'partner', hostname: 'cat-partner', public_ip: '10.0.3.130', private_ip: '192.168.10.130', 
    cpus: '1', mem: '512', storage: [10], synced_folder: 'vagrant_shared/partner'},
]

Vagrant.configure('2') do |config|

  config.vm.box = 'centos/7'

  hostname_prefix = 'dev'
  provider = 'exsi'

  if provider == 'exsi'
    # ESXI
    esxi_hostname = '10.0.1.22'
    esxi_username = 'vagrant'
    esxi_password = 'fjklsdjafksdjafksdajfks;adf'
    # one for ansible, one for public network, one for private network, set different if you want totally seperate
    esxi_virtual_network = ['Dev Cat Network', 'Dev Cat Network', 'Dev Cat Network']

    nodes.each do |node|
      config.vm.define node[:define] do |node_config|
        node_config.vm.hostname = hostname_prefix + '-' + node[:hostname]
        node_config.vm.network 'public_network', ip: node[:public_ip]
        node_config.vm.network 'private_network', ip: node[:private_ip]
        # node_config.vm.synced_folder(node[:synced_folder], '/vagrant', type: 'nfs')

        node_config.vm.provider :vmware_esxi do |esxi|
          esxi.esxi_hostname = esxi_hostname
          esxi.esxi_username = esxi_username
          esxi.esxi_password = esxi_password
          esxi.guest_virtualhw_version = '14' # ESXi 6.7
          esxi.guest_numvcpus = node[:cpus]
          esxi.guest_memsize = node[:mem]
          esxi.guest_guestos = 'centos7-64'
          esxi.guest_boot_disk_size = node[:storage]
          esxi.esxi_virtual_network = esxi_virtual_network
        end
      end
    end
  else
    # Virtualbox
    virtualbox_intnet = 'xthread'

    nodes.each do |node|
      config.vm.define node[:define] do |node_config|
        node_config.vm.hostname = hostname_prefix + '-' + node[:hostname]
        node_config.vm.network 'public_network', ip: node[:public_ip]
        node_config.vm.network 'private_network', ip: node[:private_ip], virtualbox__intnet: virtualbox_intnet
        # node_config.vm.synced_folder(node[:synced_folder], '/vagrant', type: 'nfs')

        node_config.vm.provider :virtualbox do |vb|
          vb.name = hostname_prefix + '-' + node[:hostname]
          vb.gui = false
          vb.cpus = node[:cpus]
          vb.memory = node[:mem]
          # speed up network
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
          vb.customize ["modifyvm", :id, "--ioapic", "on"]
        end
      end
    end
  end

end

=========================================================================

It seems  have something wrong when those machine doing the network action. can you please help to take a look. Thank you very much

**Comment by josenk** [comment]
Take a look at https://github.com/josenk/vagrant-vmware-esxi/issues/89.   If you downgrade to 2.2.3 does it work?

**Comment by caesarleong** [comment]
The issue still exist when downgrade Vagrant to 2.2.3.
One thing I found is the IP I set for the VM is different in ESXi, for example

{ define: 'king', hostname: 'cat-king', public_ip: '10.0.3.110', private_ip: '192.168.10.110',
cpus: '1', mem: '512', storage: [10], synced_folder: 'vagrant_shared/king'},

3 IPv4s will have for this VM, one is default for vagrant connect, another 2 should be 10.0.3.110 and 192.168.10.110.
But the other 2 will just get a wrong IP, seems come from DHCP directly.

**Comment by josenk** [comment]
I have a feeling the interfaces are being built out of order of what you expect.
  1) You might want to hard-code some MAC addresses in there to see what's going on...   

  2) Also, you are configuring the 3 interfaces on the same subnet.   I feel Vagrant doesn't handle that very well.  (It's actually Vagrant code that configures the static ip's, not the plugin).   My tests give inconsistent results when doing that.   Often things fail, but then work when I retry...   You might want to configure nic 2 & 3 on a separate subnet.

This is certainly a complex configuration that is not typical usage for Vagrant.   To get better control of the infrastructure you build, you may want to try Terraform (and my terraform/esxi plugin)....
>https://github.com/josenk/terraform-provider-esxi

**Comment by caesarleong** [comment]
Thanks for your advice. I definitely will give a try for terraform with your plugin. I will close this issue first.
