### ISSUE TITLE
problem with network

### ISSUE THREAD

**Issue by cocobear** [josenk/vagrant-vmware-esxi#94]
here is config file:
```ruby

Vagrant.configure("2") do |config|

  config.vm.box = "rhel69"

  config.vm.network 'private_network', ip: '10.0.0.111'
  config.vm.network 'private_network', ip: '192.168.0.17'

  config.vm.hostname = 'HJY001'

    config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = '192.168.1.13'

    esxi.esxi_username = 'root'
    esxi.esxi_password = 'root'

    esxi.esxi_virtual_network = ['VM Network','VM Network']

    esxi.guest_name_prefix = 'auto_'

    esxi.local_use_ip_cache = 'False'

    esxi.debug = 'true ip vmx'
  end
end
```
here is output of vagrant up:

> [root@gitlab tmp]# vagrant up
> 
> RUBY_PLATFORM: x86_64-linux
> Testing esxi connectivity
> ==> default: --- ESXi version    : VMware ESXi 6.5.0 build-13635690
> Bringing machine 'default' up with 'vmware_esxi' provider...
> ==> default: Virtual Machine will be built.
> VMware ovftool 4.3.0 (build-13981069)
> ==> default: --- Avail DS vols   : ["datastore1", "datastore3", "datastore2"]
> ==> default: --- WARNING         : esxi_disk_store not set, using "--- Least Used ---"
> ==> default: --- Avail Networks  : ["VM Network", "Management Network"]
> ==> default: --- WARNING :  config.esxi_virtual_network ["VM Network", "VM Network"] vm_network_index 2 env[:machine].config.vm.networks [[:private_network, {:ip=>"10.0.0.111", :protocol=>"tcp", :id=>"1a65bd9d-70fe-4d87-87f9-4ddadc5f7453"}], [:private_network, {:ip=>"192.168.0.17", :protocol=>"tcp", :id=>"3a64a2f2-b667-456a-a602-4c86a9a1e5bb"}], [:forwarded_port, {:guest=>22, :host=>2222, :host_ip=>"127.0.0.1", :id=>"ssh", :auto_correct=>true, :protocol=>"tcp"}]]
> ==> default: --- WARNING :  config.esxi_virtual_network ["VM Network", "VM Network", "--NotSet--"]
> ==> default: --- **WARNING         : esxi_virtual_network[2] not found, using VM Network**
> ==> default: ---   --- ESXi Summary ---
> ==> default: --- ESXi host       : 192.168.1.13
> ==> default: --- Virtual Network : ["VM Network", "VM Network", "VM Network"]
> ==> default: --- Disk Store      : datastore2
> ==> default: --- Resource Pool   : /
> ==> default: ---  --- Guest Summary ---
> ==> default: --- VM Name         : HJY001
> ==> default: --- Box             : rhel69
> ==> default: --- Box Ver         : 0
> ==> default: --- Memsize (MB)    : 1024
> ==> default: --- CPUS            : 1
> ==> default: --- Guest OS type   : rhel6-64

I add some log info to show config.vm.networks and config.esxi_virtual_network vars, focus on :
> **WARNING         : esxi_virtual_network[2] not found, using VM Network**

I only define 2 virtual network but end up with vm has 3 virtual network, because of default config has `forwarded_port` treat as virtual network, I think these is wrong .

I set 2 static ip here , but the vm starts with eth1 with ip :10.0.0.111 another is using dhcp, 
I don't know why.

**Comment by josenk** [comment]
By adding 2 `config.vm.network 'private_network'` lines, you are basically asking for 3 network interfaces  (The "vagrant management", plus the other 2 your adding).   So, you get the warning for index[2] because you didn't specify which virtual_network to use for the 3rd interface.

It's in the README and also explained here.

>https://github.com/josenk/vagrant-vmware-esxi/wiki/How-to-configure-a-static-IP-on-the-primary-interface


BTW:  It's bad practice to assign two different IPs from two different subnets on the same interface...

**Comment by cocobear** [comment]
Thanks for the reply.

Now I know why I can not assign statis IP to eth1.
Here is esxi network  Adapter Info:

<img width="1196" alt="Screen Shot 2019-11-11 at 10 44 43" src="https://user-images.githubusercontent.com/181942/68557287-52c96500-0470-11ea-9fdb-524f91b8d1dd.png">

Discovered Subnets
192.168.1.1-192.168.1.63 VLAN ID 0

I make a new Vagrantfile:
`Vagrant.configure("2") do |config|
  config.vm.box = "rhel69"
  config.vm.network 'private_network', ip: '192.168.1.67'
  config.vm.hostname = 'HJY001'
    config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = '192.168.1.13'
    esxi.esxi_username = 'root'
    esxi.esxi_password = 'root'
    esxi.esxi_virtual_network = ['New port group','VM Network']
    esxi.guest_name_prefix = 'auto_'
    esxi.local_use_ip_cache = 'False'
    esxi.debug = 'true ip vmx'
  end
end
`
if I assign static IP out of this range, it can not work.
so 
`  config.vm.network 'private_network', ip: '192.168.1.67'
`
will not work, but 
`  config.vm.network 'private_network', ip: '192.168.1.47'
I not familiar with ESXi network configure, don't know why.

**Comment by josenk** [comment]
This doesn't look like a plugin issue.   I only support the plugin.

there are many forums on the internet to help you learn networking and esxi.

**Comment by cocobear** [comment]
After a couple of days use, I found it's not problem of vlan,  the same config sometimes worked, sometime not.  If static IP config not assigned, I run `vagrant reload`  command,  most of time everything is ok.
